### ISSUE TITLE
LinkedIn Sharing doesn't work

### ISSUE THREAD

**Issue by Lyncis** [nicolasbeauvais/vue-social-sharing#108]
LinkedIn sharing doesn't provide any result.
It opens an empty window, all the content is lost. 
I tried this on different browsers and met this problem on every one of them.

![image](https://user-images.githubusercontent.com/8875863/44210516-b31a0b80-a134-11e8-9c95-b435b218a2e9.png)

Sharing of the same content on Facebook, Twitter and Telegram works well.
Are there any possible solutions to this problem?

**Comment by 4ban** [comment]
In addition to the above:

The [link](https://www.linkedin.com/shareArticle?mini=true&url=http://developer.linkedin.com&title=LinkedIn%20Developer%20Network&summary=My%20favorite%20developer%20program&source=LinkedIn) from official [website](https://developer.linkedin.com/docs/share-on-linkedin) works well only in Linux browsers: 
* Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* Opera 54.0.2952.71

And doesn't work in any other browsers such Linux Firefox or any Windows browsers.
Inserted link is trimmed to: `https://www.linkedin.com/sharing/share-offsite/?url=http%3A%2F%2Fdeveloper.linkedin.com`

**Comment by 4ban** [comment]
> Indeed, it is simply an escaping issue...

@Valdorous Do you know how to fix that?

**Comment by joe-smalley** [comment]
I am having an issue sharing on LinkedIn too. I have added the relevant OG tags detailed [here](https://www.linkedin.com/help/linkedin/answer/46687). When I inspect my page URL with the LinkedIn [inspector tool](https://www.linkedin.com/post-inspector/inspect/), at the bottom of that page my tags are shown as missing. I therefore wonder if LinkedIn is unable to scrape SPA sites whose markup is built on the frontend.

**Comment by Lyncis** [comment]
@joe-smalley I tried this as well and it doesn't work for me too. Seems like LinkedIn doesn't support it although their documentation says that it does. I ended up not using LinkedIn sharing at all

**Comment by avdept** [comment]
Have you tried it locally only? IF you try that locally it won't work, since linkedin will try to access your local link and since its most likely not accessible from outside - hence empty window

**Comment by avdept** [comment]
If you still seeing this issue, try to use linkedin share debugger - https://www.linkedin.com/post-inspector/ along with something like ngrok. I've fixed mine issue by moving to existing server so that linkedin could fetch data from provided url

**Comment by Lyncis** [comment]
Thanks! I don't work with this issue right now, but I'll check it anyway.
