### ISSUE TITLE
Blocked a frame with origin "http://example.com" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by DimaZuien** [nicolasbeauvais/vue-social-sharing#113]
There is a bug that appears when the component gets rerendered.

Steps to reproduce:
1) Open a popup by clicking on a social button (of Facebook, for example) and leave it open.
2) Make the component to rerender via v-if or just reload the current page
3) Click on a social button of another social network (Twitter, for example)

An error will be thrown
![screenshot1](https://user-images.githubusercontent.com/29693754/46530760-7ac8bb00-c8a3-11e8-9675-8b8767c5ccd9.png)

And it appears on this line:
![screenshot2](https://user-images.githubusercontent.com/29693754/46530765-7d2b1500-c8a3-11e8-8338-19fe3e2b0a1d.png)

If this info is needed:
Chrome version - 69.0.3497.100
vue-social-sharing version - 2.3.3

**Comment by MarineLB** [comment]
has this been resolved? I'm having the same issue

**Comment by nicolasbeauvais** [comment]
Hello @MarineLB, 

this is a security behavior enforced by the browser, it should work if you're testing the package with an `https` protected domain. See https://stackoverflow.com/questions/42825369/i-want-to-access-popup-functionswindow-open-with-different-domain

**Comment by mjzarrin** [comment]
I could not test it but I think, If you change `sharer` to `_blank` then sharing scope for all social media get separated in the browser. 

```
this.popup.window = $window.open(
        this.shareLink,
        '_blank',
        ...
      )
```

**Comment by ra79sta** [comment]
> Hello @MarineLB,
> 
> this is a security behavior enforced by the browser, it should work if you're testing the package with an `https` protected domain. See https://stackoverflow.com/questions/42825369/i-want-to-access-popup-functionswindow-open-with-different-domain

**Comment by boris-rebellion7** [comment]
@nicolasbeauvais Hy i have the same error on the server which has the https
![Screenshot 2023-03-01 at 18 49 40](https://user-images.githubusercontent.com/46600069/222221164-79fa2023-8aff-4826-812b-f708d2132f73.png)

**Comment by RobbeR** [comment]
any update?

**Comment by mbillahbli** [comment]
Facing same problem on my production domain. But it's working my application last release. 
working on node version: 14.15.1
now Update node version: 16.17.1 then facing this blocked error when open popup
