### ISSUE TITLE
uvue ssr network override causes hydration error

### ISSUE THREAD

**Issue by cannap** [nicolasbeauvais/vue-social-sharing#116]
Hi i have this in my my component

data  :
```js
  overriddenNetworks: {
      whatsappFix: {
        sharer: `https://api.whatsapp.com/send?text=@description%0D%0A@url`,
        type: 'popup',
        action: 'share/whatsapp/share'
      }
```
use it like so 
```html
<social-sharing
              :networks="overriddenNetworks"...

	...some other networks
    <network
                  network="whatsappFix"
                  class="ml-6"
                >
                  <div
                    style="width:24px; color:#25d366"
                    class="icon cursor-pointer"
                  >
                    <whatsapp />
                  </div>
                </network>
```
when i remove the whatsappFix the error is gone i need it to wrap with no-ssr module this only happens to the overriden network

<whatsapp> i just a global register svg component from svg-loader for vue

**Comment by nicolasbeauvais** [comment]
Thank you for raising this issue, the [latest version](https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v3.0.0-beta.2) of `Vue Social Sharing` has been released with improved support for SSR.
