### ISSUE TITLE
Getting "HTTP ERROR 400" while sharing with Twitter

### ISSUE THREAD

**Issue by abeltodev** [nicolasbeauvais/vue-social-sharing#117]
The other networks work great.

Any idea?

Thanks!

**Comment by nicolasbeauvais** [comment]
Hello @abeltodev,

I can't help you with so little information on your bug.

Feel free to re-open the issue with more details if you are still experiencing it.

**Comment by abeltodev** [comment]
Hi @nicolasbeauvais,

Thank you for your response. I'm not sure which information could help you. My code:

`
                       <social-sharing inline-template
                                        :url="seo.meta['og:url'].content"
                                        :title="seo.title"
                                        :description="seo.meta.description.content"
                                        :hashtags="seo.meta.keywords.content"
                                        twitter-user="##">
                            <div class="q-mt-md">
                                <network network="twitter">
                                    <q-btn icon="fab fa-twitter" size="sm" class="q-mr-sm">
                                        <q-tooltip>Share with Twitter</q-tooltip>
                                    </q-btn>
                                </network>
                            </div>
                        </social-sharing>
`

Version: "vue-social-sharing": "^2.3.3",
