### ISSUE TITLE
Move rollup-plugin-json to devDependencies

### ISSUE THREAD

**Issue by daniplaninc** [nicolasbeauvais/vue-social-sharing#122]
Hi,

Is there a reason rollup-plugin-json is in dependencies and not devDependencies?

I just noticed it recently due to https://www.npmjs.com/advisories/786

I opened an issue in their repository (https://github.com/rollup/rollup-plugin-json/issues/52).

**Comment by pirhoo** [comment]
Hi,

I noticed the same: unfortunately `rollup-plugin-json` comes with [a lot of dependencies](http://npm.broofa.com/?q=rollup-plugin-json):

![screenshot_2019-02-18 npmgraph - rollup-plugin-json](https://user-images.githubusercontent.com/471176/52963321-bc17be00-339f-11e9-8895-5e39fa24a248.png)

**Comment by nicolasbeauvais** [comment]
Hello @daniplaninc and @pirhoo,

This is a nice catch, I moved back `rollup-plugin-json` to devDependencies in the latest version.

Thank you.
