### ISSUE TITLE
Description and title not getting appeared on shared link in linkedin

### ISSUE THREAD

**Issue by srishti-sqm** [nicolasbeauvais/vue-social-sharing#127]
When passing props title and description to social sharing component , it is not getting displayed in linkedIN. It is taking page title tag to show title rather than title prop that has been passed.

CODE : 

                  <social-sharing url="https://github.com"
                       v-bind:title="'Event : ' + event.title"
                       v-bind:description="'Event Name : ' + event.title + '\n' + 'Event Date : ' + formatDate(event.date) + '\n' + 'Event description : ' + event.event_description + '\n'"
                       v-bind:quote="'Event Name : ' + event.title + '\n' + 'Event Date : ' + formatDate(event.date) + '\n' + 'Event description : ' + event.event_description"
                       
                      inline-template>
                    <div class="socialMediaPanel">
                       <network network="facebook">
                          <i class="fa fa-facebook"></i> <img src="static/images/fbs.svg" width="35">
                        </network>
                         <network network="twitter">
                          <i class="fa fa-twitter"></i> <img src="static/images/twt.svg" width="35">
                        </network>
                           <network network="linkedin">
                          <i class="fa fa-linkedin"></i> <img src="static/images/ldn.svg" width="35">
                        </network>
                        <network network="email">
                            <i class="fa fa-envelope"></i> <img src="static/images/eml.svg" width="35">
                      </network>
                       
                   </div>
                  </social-sharing>

**Comment by nicolasbeauvais** [comment]
Hello @srishti-sqm,

Facebook/Twitter/LinkedIn use their own graph API to fetch the data used in the sharing dialog, to customize the shared content you need to add meta tags on your page.

More info here #69

**Comment by srishti-sqm** [comment]
But How can we update the title and url(dynamic title and url link to share) each time linkedin is clicked to share. And even it is stripping query params in url prop in linkedin share.
