### ISSUE TITLE
How can we update the title and url(dynamic title and url link to share) each time linkedin is clicked to share. And even it is stripping query params in url prop in linkedin share.

### ISSUE THREAD

**Issue by srishti-sqm** [nicolasbeauvais/vue-social-sharing#128]
But How can we update the title and url(dynamic title and url link to share) each time linkedin is clicked to share. And even it is stripping query params in url prop in linkedin share.

_Originally posted by @srishti-sqm in https://github.com/nicolasbeauvais/vue-social-sharing/issues/127#issuecomment-475513018_

**Comment by srishti-sqm** [comment]
Code : 

                  <social-sharing url="https://github.com?event_id=1"
                       v-bind:title="'Event : ' + event.title"
                       v-bind:description="'Event Name : ' + event.title + '\n' + 'Event Date : ' + formatDate(event.date) + '\n' + 'Event description : ' + event.event_description + '\n'"
                       v-bind:quote="'Event Name : ' + event.title + '\n' + 'Event Date : ' + formatDate(event.date) + '\n' + 'Event description : ' + event.event_description"
                       
                      inline-template>
                    <div class="socialMediaPanel">
                       <network network="facebook">
                          <i class="fa fa-facebook"></i> <img src="static/images/fbs.svg" width="35">
                        </network>
                         <network network="twitter">
                          <i class="fa fa-twitter"></i> <img src="static/images/twt.svg" width="35">
                        </network>
                           <network network="linkedin">
                          <i class="fa fa-linkedin"></i> <img src="static/images/ldn.svg" width="35">
                        </network>
                        <network network="email">
                            <i class="fa fa-envelope"></i> <img src="static/images/eml.svg" width="35">
                      </network>
                       
                   </div>
                  </social-sharing>

In index.html : 
<meta name="title" property="og:title" content="My Shared Article Title">
<meta name="url" property="og:url" content="https://github.com?event_id=1">

**Comment by srishti-sqm** [comment]
In index.html :

<meta name="title" property="og:title" content="My Shared Article Title">
<meta name="url" property="og:url" content="https://github.com?event_id=1">

**Comment by nicolasbeauvais** [comment]
Hello @srishti-sqm,

Open graph tag strategy is outside of the scope of this package. You can find a [lot of resource](https://neilpatel.com/blog/open-graph-meta-tags/) on how to setup dynamic meta tags [using query parameters for example](https://stackoverflow.com/questions/34281862/dynamic-facebook-open-graph-tags-possible).

But it has to be made on your backend as Facebook / Linkedin and other services will not render the Javascript of your pages.
