### ISSUE TITLE
Permission error in IE11

### ISSUE THREAD

**Issue by dylankelly** [nicolasbeauvais/vue-social-sharing#130]
Sharing causes a console error in IE11 - `Error in v-on handler: "Error: Permission denied"`

This can be observed by visiting this fiddle in IE11 http://jsfiddle.net/2b5fzrj9/1/embedded/result clicking the facebook link and opening javascript console. The window opens, but with console error seen in the below screenshot.

![bs_win10_IE_11 0](https://user-images.githubusercontent.com/2186721/55694288-d9a7f200-59f6-11e9-917a-21a1979d77d9.jpg)

This appears to be caused by assigning `window.open` to `this.popup.window`  in https://github.com/nicolasbeauvais/vue-social-sharing/blob/master/src/social-sharing.js#L217. Assigning to a variable instead fixes the issue, Example fiddle here http://jsfiddle.net/2b5fzrj9/2/embedded/result. 

As you are not using `this.popup.window` outside of openSharer, the workaround I have is to assign to a local variable, I will add this to a PR.

**Comment by nicolasbeauvais** [comment]
I closed the issue as the pull request is merged.

Feel free to re-open the issue if needed!
