### ISSUE TITLE
why share to FB only get the first hashtag?

### ISSUE THREAD

**Issue by huynhmaihoanghuy** [nicolasbeauvais/vue-social-sharing#132]
Can I share more hashtags?

**Comment by LTFENG** [comment]
why do you close this issue ? Any solution for this ?

**Comment by nicolasbeauvais** [comment]
Hello @LTFENG,

Only one hashtag can be shared, this is a Facebook limitation, see https://developers.facebook.com/docs/sharing/reference/share-dialog/

Thank you.
