### ISSUE TITLE
sharing by sms with iOs and iMessage

### ISSUE THREAD

**Issue by tpin85** [nicolasbeauvais/vue-social-sharing#133]
Hi, 
Sharing by sms is in trouble on iOs and iMessage. Work fine on android. The 'description' param is push into the recipients phones numbers.
You can see in screenshot the issue in iMessage.

<img width="675" alt="Capture d’écran 2019-04-11 à 10 59 53" src="https://user-images.githubusercontent.com/26658599/55962984-3d8a1f00-5c72-11e9-8794-83c3e353a9af.png">

Thanks

**Comment by nicolasbeauvais** [comment]
Hello @tpin85,

It appears that IOS use a non-standard parsing for the SMS body ([more info here](https://weblog.west-wind.com/posts/2013/Oct/09/Prefilling-an-SMS-on-Mobile-Devices-with-the-sms-Uri-Scheme#Body-only)).

This should now work with the latest version 2.4.4.

Thank you for reporting the error.

**Comment by MaeseppTarvo** [comment]
@nicolasbeauvais Tested on 2.4.6 and still an issue.

**Comment by marshallino16** [comment]
Tested on 2.4.7 and still an issue

**Comment by nicolasbeauvais** [comment]
Hello @MaeseppTarvo and @marshallino16, I do not own any IOS device to debug this issue, please feel free to open a PR with a fix if you can.

**Comment by holygekko** [comment]
it should use an & instead of ;
```
"sms_ios": {
    "sharer": "sms:&body=@url%20@description",
    "type": "direct"
  }
```

see this SO answer: https://stackoverflow.com/questions/39529099/trying-to-send-sms-in-ios-10-is-sms-protocol-broken/39572784#39572784

I temporally fixed it by overwriting the sms_ios sharer via the networks property (https://github.com/nicolasbeauvais/vue-social-sharing#extending-the-network-list)

**Comment by VictorVermeulen** [comment]
> it should use an & instead of ;
> 
> ```
> "sms_ios": {
>     "sharer": "sms:&body=@url%20@description",
>     "type": "direct"
>   }
> ```
> 
> see this SO answer: https://stackoverflow.com/questions/39529099/trying-to-send-sms-in-ios-10-is-sms-protocol-broken/39572784#39572784
> 
> I temporally fixed it by overwriting the sms_ios sharer via the networks property (https://github.com/nicolasbeauvais/vue-social-sharing#extending-the-network-list)

Does this mean you needed to update to version 3.x as that github link suggests? I tried overwriting the sms_ios sharer with version 2.4.7 and I think that doesn't work. However I am not sure I can update to version 3.x since I am not using SSR or Vue 3.x

**Comment by nicolasbeauvais** [comment]
@holygekko thank you for the code sample, the latest version as been updated with your suggested change!

**Comment by nicolasbeauvais** [comment]
@VictorVermeulen Indeed it was not very clear in the documentation, I updated it. The v3 of Vue Social Sharing is fully compatible with Vue2 and non-SSR projects. But I will keep it in beta until Vue3 is released in case something need to be changed to support it.
