### ISSUE TITLE
Send Url as a link while sharing via gmail

### ISSUE THREAD

**Issue by srishti-sqm** [nicolasbeauvais/vue-social-sharing#134]
I want to send url as a link in which we can send it either as an anchor tag where display text would be different and on clicking that display tag user gets redirected to the shared url.

As in , Sign up Today should be text for url to be shared and on clicking of that text user should get redirected to specific url.

**Comment by nicolasbeauvais** [comment]
Hello @srishti-sqm,

I'm not sure to understand what you're trying to achieve here but maybe you could use dynamic properties if what you need is a dynamic button?

If not, please explain your issue in more details with code samples.

Thank you
