### ISSUE TITLE
Many link buttons will duplicate a lot of code

### ISSUE THREAD

**Issue by tvld** [nicolasbeauvais/vue-social-sharing#138]
I have a list with +100 share buttons and would like to load only _one_ sharing modal. Each button invokes the modal to share a different url.

How can we pass the url to the sharing modal? I could use Vuex but is that not overkill?

Would be nice to have two components: one a button, the other the content. Now it's included in one.

**Comment by nicolasbeauvais** [comment]
Hello @tvld,

you can use vue binding to dynamically change the social sharing component properties:

```html
<social-sharing 
  :url="dynamicUrl"
  :title="dynamicTitle">
</social-sharing>
```
