### ISSUE TITLE
Share on Email

### ISSUE THREAD

**Issue by vanholler** [nicolasbeauvais/vue-social-sharing#139]
Pleas add to your package function share on Email. Because we are often use share in social and Email. But need install another package. Its realy add in one package )))) 
Thank for your awesome npm-package))))

**Comment by nicolasbeauvais** [comment]
Hello @vanholler,

you can already share by email using:

```html
<network network="email">
    <i class="fa fa-envelope"></i> Email
</network>
```

as stated in the documentation.

**Comment by umervservices** [comment]
it giving Cannot read property 'getDomain' of undefined error what are the possibilities

**Comment by frakkio** [comment]
> it giving Cannot read property 'getDomain' of undefined error what are the possibilities
I'm using nuxtjs with SSR and got the same issue, only for the email, clicking the link shows this error:
`TypeError: Cannot read property 'getDomain' of undefined`,
other socials are working fine.

this is my code:
`    <ShareNetwork network="email" url="https://github.com/nicolasbeauvais/vue-social-sharing" description="email example" title="share this page by email">
        <span class="icon icon-envelope"></span>
    </ShareNetwork>`

`"vue-social-sharing": "^3.0.2" `
