### ISSUE TITLE
Popup doesn't open in center on dual monitor setup.

### ISSUE THREAD

**Issue by abhish3kk** [nicolasbeauvais/vue-social-sharing#14]
If I open popup on my main screen its working absolutely fine. However, the same popup opens on the left of screen. 
![popup](https://cloud.githubusercontent.com/assets/16529043/23739219/5ce1d7e8-04c3-11e7-8316-fd97fa5b72e6.png)

I have used this as a solution for a similar problem: http://stackoverflow.com/questions/4068373/center-a-popup-window-on-screen/32261263.

**Comment by nicolasbeauvais** [comment]
@abhish3kk Thank you for this solution, I'm currently on holidays so I will not be able to make the change at this time. If you need it quickly feel free to make a pull request, otherwise I will look into it in the following week :)

**Comment by nicolasbeauvais** [comment]
@abhish3kk Your solution worked great ! (except for Weibo who apparently update the popup position badly on the second screen).

The change is available in the latest version https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v2.1.4. Thank you for your contribution :)
