### ISSUE TITLE
Library size is 75 KB

### ISSUE THREAD

**Issue by HawkeyePierce89** [nicolasbeauvais/vue-social-sharing#141]
75 KB – why so many?

![image](https://user-images.githubusercontent.com/25603805/58248788-c57d4180-7d65-11e9-84ff-1c82bd9d7978.png)

**Comment by nicolasbeauvais** [comment]
Hello @HawkeyePierce89,

I do not know what kind of tools you're using but I suppose this is the size before minification.
[You can see on GitHub](https://github.com/nicolasbeauvais/vue-social-sharing/blob/master/dist/vue-social-sharing.min.js) that the minified version of the library is ~5kb which result in ~2kb gzipped.

You're welcome to contribute to the library if you want to improve it even further.

**Comment by HawkeyePierce89** [comment]
Why you don't use minified version by default? 
https://github.com/nicolasbeauvais/vue-social-sharing/blob/588d8182bd3deeaa9edc726d575026e7fe45849f/package.json#L75

**Comment by HawkeyePierce89** [comment]
ok, sorry, I checked this plugin with vue-cli and diff is only 5 KB. Usually plugin works correct

![image](https://user-images.githubusercontent.com/25603805/58288040-31d66000-7dbb-11e9-9bcd-eeee525e440e.png)

sorry to bother you

**Comment by peoray** [comment]
> ok, sorry, I checked this plugin with vue-cli and diff is only 5 KB. Usually plugin works correct
> 
> ![image](https://user-images.githubusercontent.com/25603805/58288040-31d66000-7dbb-11e9-9bcd-eeee525e440e.png)
> 
> sorry to bother you

@HawkeyePierce89 Can you explain what you mean here? Did you do anything differently
