### ISSUE TITLE
Twitter share on mobile (only) includes a blank hashtag "#"

### ISSUE THREAD

**Issue by krisnicolaou** [nicolasbeauvais/vue-social-sharing#143]
Hi there. Only when sharing on mobile to Twitter, not including any hashtags puts a blank hashtag within the tweet e.g.:

> Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Curabitur blandit tempus porttitor. http://domain.com # via @testing‬

```
<social-sharing 
	title="Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Curabitur blandit tempus porttitor." 
	description="Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Curabitur blandit tempus porttitor." 
	quote="Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Curabitur blandit tempus porttitor." 
	url="http://domain.com" 
	hashtags=""
	twitter-user="testing‬"
	inline-template
>
	<div class="col d-flex mx-auto spread-the-word-btns social-sharing">
		<network network="facebook">
			<a href="javascript:void(0);" class="btn btn-primary" role="button">Facebook</a>
		</network>
		<network network="twitter">
			<a href="javascript:void(0);" class="btn btn-primary" role="button">Twitter</a>
		</network>
	</div>
</social-sharing>
```

I have tried with and without the `hashtags` attribute. 

Let me know. Thank you.

**Comment by krisnicolaou** [comment]
Identified the issue, but cannot get to send a pull request today. When including the blank 'hashtags' key (no value, i.e. "...&hashtags=") within the "sharer" URL, the Twitter app on iPhone includes a hashtag with no hashtag content.

**Comment by nicolasbeauvais** [comment]
Hello @krisnicolaou,

thank you for reporting the issue and investigate a solution.

The [latest version](https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v2.4.5) of vue social sharing has been patched.

**Comment by krisnicolaou** [comment]
Hi @nicolasbeauvais 

Thank you for looking into this issue. I tested on iOS and the issue still seems to persist. 
**iPhone**
Software Version: 12.2
Model Name: iPhone Xs

Thanks again,
Kris
