### ISSUE TITLE
how could i  add dynamic Url in social sharing

### ISSUE THREAD

**Issue by vishalsingh0919** [nicolasbeauvais/vue-social-sharing#144]
i am unable to add dynamic url instead of static to share
`  <social-sharing
                          url="https://vuejs.org/">`

**Comment by vishalsingh0919** [comment]
i am unable to add dynamic url instead of static to share 
 <social-sharing
  url="https://vuejs.org/">

**Comment by alainvd** [comment]
You can use a computed property (https://vuejs.org/v2/guide/computed.html)
Then use this code:
<social-sharing :url=YOUR_COMPUTED_PROPERTY_VARIABLE_NAME>

**Comment by nicolasbeauvais** [comment]
Thank you for the help @alainvd.

**Comment by vishalsingh0919** [comment]
its showing an error when i am using this `:url` will you please share some code with me that can help

**Comment by vishalsingh0919** [comment]
its done!!  thankyou @alainvd
