### ISSUE TITLE
please add weibo support

### ISSUE THREAD

**Issue by sinchang** [nicolasbeauvais/vue-social-sharing#15]
just add below code in `src/network.js`

```
weibo: {
    sharer: 'http://service.weibo.com/share/share.php?url=@url&title=@title',
    type: 'popup'
  }
```

thanks.

😃

**Comment by nicolasbeauvais** [comment]
Hello @sinchang, Weibo support as been added in the latest update https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v2.1.3

Thank you for your contribution :)
