### ISSUE TITLE
support for web share api

### ISSUE THREAD

**Issue by svewag** [nicolasbeauvais/vue-social-sharing#152]
Hello,

i would like to see / add the possibility to invoke the web share api.

https://developers.google.com/web/updates/2016/09/navigator-share

Any suggestions how to implement it in the current concept?

**Comment by nicolasbeauvais** [comment]
Hello @svewag,

the web share API looks interesting but I think that for now, it is a little outside the scope of this package which is to provide simple social sharing.

Today the library architecture is not adapted to easily add something like that so you will have to "create" everything if you want to make a PR.

I will definitely keep an eye on it if it gets supported on more browsers / platform.

**Comment by arkhamvm** [comment]
Hello.
Now it supported by ~60% of browsers and very useful on mobile devices. Can you add it, please?
https://caniuse.com/web-share
