### ISSUE TITLE
Don't stop the console error when closed Popup.

### ISSUE THREAD

**Issue by takase-eri** [nicolasbeauvais/vue-social-sharing#156]
After opening a new popup without closing the existing one, closing the popup won't stop the console error.

console error:
```
Uncaught TypeError: Cannot read property 'closed' of undefined
```

You created if open new popup when already exist another popup, `openSharer` close old popup and fire change event.
I think error caused by that function does not work enough.
Please confirm.

I use latest version (2.4.5)

**Comment by Sandalf** [comment]
I'm also getting this error in version 2.4.6
