### ISSUE TITLE
Cannot use special characters

### ISSUE THREAD

**Issue by Flame2057** [nicolasbeauvais/vue-social-sharing#16]
When using `<social-sharing :title="'C#'">` or `:title="'C++'"`, the characters `+` or `#` are not there in the sharing windows for both twitter and facebook.

**Comment by Flame2057** [comment]
You probably need to URL escape the strings before adding them to the URLs

**Comment by Flame2057** [comment]
Fixed it by calling `encodeURIComponent` on my title

**Comment by nicolasbeauvais** [comment]
Thank you for the bug report & fix. `encodeURIComponent` is now used to encode title / description & quotes by default.
