### ISSUE TITLE
Navigator is not defined

### ISSUE THREAD

**Issue by jdospina95** [nicolasbeauvais/vue-social-sharing#160]
I am currently facing an issue when trying to build my project. Vue social sharing module is throwing an error at `vue-social-sharing.common.js` line 235 `var ua = navigator.userAgent.toLowerCase();` which says that navigator is not defined. I tried changing the version of vue social sharing to see if the error maybe was in the latest versions but tried all the versions from 0.x.x to 2.x.x and had no luck getting rid of that error.

My project is built on Nuxt 2.8.1

**Comment by nicolasbeauvais** [comment]
Hello @jdospina95,

indeed the `navigator` object is only available in the browser and not on the server side.

Could you try to follow the instructions on [this page](https://nuxtjs.org/faq/window-document-undefined/) so that vue social sharing gets only loaded in the browser?

Thank you.

**Comment by kayakmind** [comment]
I'm running into a similar error message using Gridsome when I attempt to build the app. 

```
Failed to render /posts/how-to-teach-science-through-play-with-a-cheap-pulley-and-rope
ReferenceError: navigator is not defined
    at a.createSharingUrl
```
Any suggestions? Thanks for creating this -- it's working terrific in development.

**Comment by findtoni** [comment]
@jdospina95 This solution worked for me - https://github.com/nicolasbeauvais/vue-social-sharing/issues/26#issuecomment-304405995

**Comment by kayakmind** [comment]
@jdospina95 Thanks!

**Comment by PVautour** [comment]
Wrapping the element with <no-ssr></no-ssr> was the only thing that worked for page reload in my case. Here is the original post where I found the solution:

https://github.com/nicolasbeauvais/vue-social-sharing/issues/26#issuecomment-409268732
