### ISSUE TITLE
StaticClass property in network component

### ISSUE THREAD

**Issue by Anatolych97** [nicolasbeauvais/vue-social-sharing#161]
How can i set staticClass property for network component?  I can't find any props/attrs or another opportunity to do it.

**Comment by nicolasbeauvais** [comment]
Hello @Anatolych97,

as shown in [this exemple](https://codesandbox.io/s/vue-template-sh0m0?fontsize=14&module=%2Fsrc%2Fcomponents%2FHelloWorld.vue) you can use the  `class` and `style` property on the `network` component.
