### ISSUE TITLE
Error after dynamic import of social sharing script

### ISSUE THREAD

**Issue by shubhra14** [nicolasbeauvais/vue-social-sharing#166]
Hi,
I'm getting this error when I try to dynamically import the component

> Unknown custom element: `<social-sharing>` - did you register the component correctly?

This is how I'm using it in my main.js
```

//This works
//var SocialSharing = require('vue-social-sharing');

//doesn't work
const SocialSharing = () => import(
  /* webpackChunkName: "postlists" */
  '@/components/grids/utility/PostListAuthorPopup')

Vue.use(SocialSharing);
```

**Comment by nicolasbeauvais** [comment]
Hi @shubhra14, it appears that you are not loading vue-social-sharing in your second example but `@/components/grids/utility/PostListAuthorPopup`
