### ISSUE TITLE
Share to clipboard?

### ISSUE THREAD

**Issue by ajmas** [nicolasbeauvais/vue-social-sharing#169]
Noticed that there isn't a share link to clipboard option. Would this be something seen as worth adding? I appreciate it isn't a social share, but it is a sharing option.

**Comment by bustarice** [comment]
This [codepen](https://codepen.io/PJCHENder/pen/jamJpj?editors=1010) along with using [vue-clipboard](https://github.com/Inndy/vue-clipboard2) me modify my component to do something like this:

```
<input ref="hiddenLink" type="hidden" id="page-url" :value="'https://example.com' + $route.path">

<b-link class="copy-button" @click="$refs.hiddenLink.setAttribute('type', 'text'); $refs.hiddenLink.select(); $copyText($refs.hiddenLink.value, container); $refs.hiddenLink.setAttribute('type', 'hidden')><i class="fas fa-copy fa-2x"></i></b-link>
```

**Comment by nicolasbeauvais** [comment]
Thank you for raising this issue. If you need this feature please feel free to open a PR for it
