### ISSUE TITLE
How to share to facebook with featured Image?

### ISSUE THREAD

**Issue by muhghazaliakbar** [nicolasbeauvais/vue-social-sharing#17]

**Comment by nicolasbeauvais** [comment]
You can't choose the image of a Facebook share with `vue-social-sharing`, Facebook will use it's graph API to fetch the image directly on the link you used. So if you share the link "http://myproject.com/" the page http://myproject.com/ should define the following og meta tag, allowing you to choose which image will be displayed:

```html
<meta property="og:image" content="http://myproject.com/myimage.jpg" />
```

more info here: https://developers.facebook.com/docs/sharing/best-practices

**Comment by kgrosvenor** [comment]
Can you dynamically change this inside a Single Page Application?

**Comment by nicolasbeauvais** [comment]
@kgrosvenor Sure, you just need to change the meta according to the URL of your SPA.

Here is a tutorial that covers the subject:
https://code.tutsplus.com/tutorials/adding-social-sharing-in-a-nodejs-single-page-application--cms-25530
