### ISSUE TITLE
infinite interval

### ISSUE THREAD

**Issue by kiselevAlex** [nicolasbeauvais/vue-social-sharing#177]
https://github.com/nicolasbeauvais/vue-social-sharing/blob/50e898c74f55ea81003170327f2dbd2750093f18/src/social-sharing.js#L228-L229

infinite interval if you click on the 'SocialSharingNetwork' several times

**Comment by nicolasbeauvais** [comment]
Thank you for raising this issue, the [latest version](https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v3.0.0-beta.2) of `Vue Social Sharing` has been released with a fix for this bug.
