### ISSUE TITLE
Facebook share doesn't work properly when using props on social sharing component

### ISSUE THREAD

**Issue by MrToxy** [nicolasbeauvais/vue-social-sharing#179]
I have the social share funcionality has a component:

```javascript
<social-sharing :title="title" :description="description" :quote="quote" :hashtags="hashtags" :twitter-user="twitterUser" :url="url" inline-template>
  <div>
    <network aria-label="facebook" network="facebook">
      <font-awesome-icon :icon="['fab', 'facebook-f']" />
    </network>

    <network network="twitter" aria-label="twitter">
      <font-awesome-icon :icon="['fab', 'twitter']" />
    </network>

    <network network="pinterest" aria-label="pinterest">
      <font-awesome-icon :icon="['fab', 'pinterest-p']" />
    </network>

    <network network="email" aria-label="email">
      <font-awesome-icon :icon="['fas', 'envelope']" />
    </network>
  </div>
</social-sharing>
```

It receives some props from the parent and everything works fine except for facebook.

This is the test data being passes as props:
```
title="The Progressive JavaScript Framework"
description="Intuitive, Fast and Composable MVVM for building interactive interfaces."
quote="Vue is a progressive framework for building user interfaces."
hashtags="vuejs,javascript,framework"
```

every other network outputs:
![Screenshot 2019-12-05 at 16 24 54](https://user-images.githubusercontent.com/19191292/70253807-d75f8880-177b-11ea-9881-8e7395bc8813.png)

but facebook outputs:
![Screenshot 2019-12-05 at 16 25 46](https://user-images.githubusercontent.com/19191292/70253887-fe1dbf00-177b-11ea-8c10-662303e8415b.png)

**Comment by SimpleBackEndProgrammer** [comment]
The problem is the "url" property is set but it's value is an empty string. So the social-sharing component doesn't try to set window.location.href value as it's default value, but uses empty string from the "url" property. So this is not a bug. Try to assign smth to the "url" or even remove the :url="url"  binding if you want current href to be shared.

**Comment by MrToxy** [comment]
> The problem is the "url" property is set but it's value is an empty string. So the social-sharing component doesn't try to set window.location.href value as it's default value, but uses empty string from the "url" property. So this is not a bug. Try to assign smth to the "url" or even remove the :url="url" binding if you want current href to be shared.

that does seem to have fixed the issue, thanks.
