### ISSUE TITLE
How to detect window popup are opened or closed?

### ISSUE THREAD

**Issue by muhghazaliakbar** [nicolasbeauvais/vue-social-sharing#18]
Hi, sorry i'm newbie in vue.js and javascript, i need to add some stuff when the social sharing popup window are closed. 
I need to detect the popup are closed, then i execute some function :)

**Comment by nicolasbeauvais** [comment]
Hello @muhghazaliakbar,

I just released a new version of `vue-social-sharing` (2.2.0) https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v2.2.0 that add an event when a popup is closed.

The events are documented in the readme https://github.com/nicolasbeauvais/vue-social-sharing#available-events

Hope this solve your issue :)

**Comment by muhghazaliakbar** [comment]
Ah that's very cool thank you!
