### ISSUE TITLE
Facebook share breaks when using "#" on the hashtags option

### ISSUE THREAD

**Issue by MrToxy** [nicolasbeauvais/vue-social-sharing#181]
I found that if you use `#` in your hashtags it breaks facebook share option:

```javascript
      url: 'https://www.google.com',
      title: 'Nolan',
      description: 'Ut voluptatem sequi fugit facere omnis doloremque qui.',
      quote: 'quote',
      hashtags: 'hereWeAre',
```
Will yield 
![Screenshot 2019-12-09 at 11 48 24](https://user-images.githubusercontent.com/19191292/70433506-d67b6f00-1a79-11ea-9f95-ffc706c9f9a7.png)

While 
```javascript
{
      url: 'https://www.google.com',
      title: 'Nolan',
      description: 'Ut voluptatem sequi fugit facere omnis doloremque qui.',
      quote: 'quote',
      hashtags: '#hereWeAre',
}
```
Will yeild

![Screenshot 2019-12-09 at 11 49 38](https://user-images.githubusercontent.com/19191292/70433582-0a569480-1a7a-11ea-8f83-fd2d6372f195.png)

A quick way to solve this was to simply sanitize the url with a regex like this:

`tags.replace(/(#)/g,"")` but this should probably be addressed internally to prevent unexpected behaviour

**Comment by nicolasbeauvais** [comment]
Hello @MrToxy, this is indeed the behavior of Facebook, we pass the params as received to build the link. I could indeed modify the core of the package to avoid this particular issue.

**Comment by MrToxy** [comment]
> Hello @MrToxy, this is indeed the behavior of Facebook, we pass the params as received to build the link. I could indeed modify the core of the package to avoid this particular issue.

alright, no worries. can I close it?

**Comment by nicolasbeauvais** [comment]
@MrToxy done :)
