### ISSUE TITLE
Accessibility: aria-role="link"

### ISSUE THREAD

**Issue by Merott** [nicolasbeauvais/vue-social-sharing#182]
The `span` that's used for registering clicks isn't accessible at the moment, meaning that screen readers can't detect those sharing links.

From what I understand about accessibility, they should either be `a` tags, or we should set the `aria-role="link"` and also set the `href` property on the `span`:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_link_role

**Comment by nicolasbeauvais** [comment]
Hello @Merott, accessibility should indeed be improved in this package, I will take a look at your suggestions for the next minor release. Thank you.

**Comment by nicolasbeauvais** [comment]
The [latest version](https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v3.0.0-beta.2) of `Vue Social Sharing` has been released, the sharing component now default to an `a` tag.
