### ISSUE TITLE
Accessing data inside network tags

### ISSUE THREAD

**Issue by EvilJimJafar** [nicolasbeauvais/vue-social-sharing#186]
I can't access data within the **network** tags.

    async asyncData (context) {
      // ... get some data
      return {
        post: {
          uid: response.uid,
          // ...
        },
        dataFetched: true
      }
    }

...

    <div id="blog-page" v-if="dataFetched">
      <h1 class="page-title">{{ post.title }}</h1>
      <social-sharing
        :url="sharingUrl"
        :title="post.title"
        :description="post.synopsis"
        :quote="post.synopsis"
        :hashtags="post.tags.join(',')"
        inline-template
      >
        <span>
          <network network="facebook">
            <i class="fa fa-facebook"></i> {{ post ? post.title : 'nada' }}
          </network>
        </span>
     </social-sharing>
    </div>

Always shows 'nada'.

What's going on? **post** is accessible everywhere else and the **social-sharing** component has no problem reading it.

**Comment by hleon57** [comment]
I have the same problem. The funny thing is I can access the data it in one component but not in another. Any ideas ?

**Comment by hleon57** [comment]
@EvilJimJafar this solved my issue:

https://github.com/nicolasbeauvais/vue-social-sharing/issues/51#issuecomment-335261284

add $parent to the variables better explained in the issue

**Comment by EvilJimJafar** [comment]
> @EvilJimJafar this solved my issue:
> 
> [#51 (comment)](https://github.com/nicolasbeauvais/vue-social-sharing/issues/51#issuecomment-335261284)
> 
> add $parent to the variables better explained in the issue

That worked for me, thanks @hleon57 !
