### ISSUE TITLE
Local event how to access network and url properties?

### ISSUE THREAD

**Issue by gerbenqikker** [nicolasbeauvais/vue-social-sharing#188]
When I'm using the code from the documentation:

```
<some-component>
    <social-sharing @open="open()" @change="change()" @close="close()">
    </social-sharing>
</some-component>
```

And have a method called `open()` - how do I access the network and url parameters that the event emits? I have tried many ways but have not succeeded yet.

Thanks :-)

**Comment by rocchidavide** [comment]
It works without parenthesis: 
`<social-sharing @open="open" @change="change" @close="close">`

Please, fix the documentation :)

**Comment by nicolasbeauvais** [comment]
Common, making a PR for that one would have taken 30s :rofl:
