### ISSUE TITLE
Facebook opens in browser rather than app

### ISSUE THREAD

**Issue by michaelsimmonds** [nicolasbeauvais/vue-social-sharing#189]
I noticed that the facebook sharing option automatically opens in the browser. Would it be a good idea for this to open in the facebook app if the user has this on their phone/tablet?

**Comment by nicolasbeauvais** [comment]
Hello @michaelsimmonds, I think this is already handled by the phone/tablet OS. If not I need to find a workaround for that.

**Comment by giddens9527** [comment]
I think it's not handled. We are also facing this issue.
