### ISSUE TITLE
Component uses Title As Text for Twitter

### ISSUE THREAD

**Issue by Andrewsuares** [nicolasbeauvais/vue-social-sharing#190]
Hello,

I've passed some text in the TEXT param. It appears that the component does not send the TEXT. It seems to convert the title param to text for Twitter. Can you make it so that it uses the TEXT param that is passed for Twitter.

https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/web-intent

**Comment by nicolasbeauvais** [comment]
Hello @Andrewsuares, It was a deliberate choice to use the `title` property for text on Twitter instead of the description as Twitter enforce a smaller text format and does not support title + description.
