### ISSUE TITLE
Predefined message for LinkedIn?

### ISSUE THREAD

**Issue by EvanAgee** [nicolasbeauvais/vue-social-sharing#192]
Thanks for the hard work! Is there a way to provide a pre-defined message when sharing on LinkedIn?

**Comment by nicolasbeauvais** [comment]
Hello @EvanAgee,
You can use the `title` and `description` property for that.

**Comment by rpankaj** [comment]
@EvanAgee is this solved?
I have exactly same requirement but failed to do it. I need a solution.
