### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by daohuy34** [nicolasbeauvais/vue-social-sharing#193]
every time I refresh the page I get this error

**Comment by isuke01** [comment]
Yep same issue with NUXT, im using version of Vue social sharing `2.4.7`

**Comment by paramono** [comment]
To fix this issue on Nuxt, wrap your social-sharing component with <client-only>
https://nuxtjs.org/api/components-client-only/

**Comment by isuke01** [comment]
Yep, that was how I solved this issue, but this is not perfect solution :/

**Comment by nicolasbeauvais** [comment]
Thank you for raising this issue, the [latest version](https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v3.0.0-beta.2) of `Vue Social Sharing` has been released with improved support for SSR.
