### ISSUE TITLE
WhatsApp not working in Firefox

### ISSUE THREAD

**Issue by etn-egg** [nicolasbeauvais/vue-social-sharing#194]
Sharing on WhatsApp uses the URL `api.whatsapp.com/send?text=` which does not load any styling when used on Firefox:

![image](https://user-images.githubusercontent.com/40357671/75867090-f793f780-5dfd-11ea-9278-23e1246e730b.png)

The solution appears to be to use `web.whatsapp.com/send?text=`; although the official docs say to use `wa.me/?text=`:
https://faq.whatsapp.com/en/26000030/

Hopefully it's as easy as updating `src/networks.json#L73`:
https://github.com/nicolasbeauvais/vue-social-sharing/blob/master/src/networks.json#L73

If you require a pull request please let me know :)

**Comment by nicolasbeauvais** [comment]
Hello @etn-egg, thank you for raising this issue, this will be fixed in the next release!
