### ISSUE TITLE
Sharing url with params fails in Gmail android app

### ISSUE THREAD

**Issue by Adrian-Juganaru** [nicolasbeauvais/vue-social-sharing#196]
Sharing a link works on all major mail clients, with one exception:

If the url is having params it is stripped in Gmail android app

Ex: [www.example.com](www.example.com) is working, but [www.example.com?param1=foo&param2=bar](www.example.com?param1=foo&param2=bar) becomes [www.example.com?param1](www.example.com?param1) in Gmail android app. It works great in gmail in browser though...

It seems to be a common problem (see [https://stackoverflow.com/questions/59305860/gmail-app-stripping-out-equals-sign-in-mailto-body](https://stackoverflow.com/questions/59305860/gmail-app-stripping-out-equals-sign-in-mailto-body) ), but I wonder if you know a way to fix this. Thanks!

**Comment by nicolasbeauvais** [comment]
Indeed, I need to try the double encoding mentioned in the StackOverflow thread you linked to see if that can solve it.
