### ISSUE TITLE
Set props per network?

### ISSUE THREAD

**Issue by kyotoprotokollet** [nicolasbeauvais/vue-social-sharing#197]
Is there, or could you add, a way to set the props per network?

Many CMS:s and social media plugins adds fields for inputting data to specific networks. Like "Facebook  description" and "Twitter description" etc. However, it seems I can only set data that will be used by all networks, not specific data per network.

**Comment by nicolasbeauvais** [comment]
Hello @kyotoprotokollet, Thank you for raising this issue, the [latest version](https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v3.0.0-beta.2) of `Vue Social Sharing` has been released with only one component making it easier to do exactly that!
