### ISSUE TITLE
[feature] Fire an event when share has been posted

### ISSUE THREAD

**Issue by Residu** [nicolasbeauvais/vue-social-sharing#20]
Hi,

Is it possible to add an event when the share has been validated?

Thanks for your work dude!

**Comment by nicolasbeauvais** [comment]
It looks possible with Facebook using the javascript SDK:
https://developers.facebook.com/docs/sharing/reference/share-dialog

It appears that Twitter removed this features some years ago.

Some other sharing libraries couldn't find a workaround for this: 
https://github.com/carrot/share-button/issues/167

I'm closing this issue as I can't provide any solution for it. If you find something interesting feels free to open it again :)
