### ISSUE TITLE
Window size is too small

### ISSUE THREAD

**Issue by BenjaminRosell** [nicolasbeauvais/vue-social-sharing#201]
Hello there ! 

This is an awesome component ! I was wondering if there was a way to control the size of the pop up window? Sometimes it's very small. See some examples ahead 

That would really be awesome :) Thanks ! 

<img width="879" alt="image" src="https://user-images.githubusercontent.com/912624/77817621-9bda2880-70a2-11ea-8837-7f9620f1916b.png">
<img width="581" alt="image" src="https://user-images.githubusercontent.com/912624/77817625-a5639080-70a2-11ea-9500-7346498815dc.png">

**Comment by nicolasbeauvais** [comment]
Hello @BenjaminRosell, 
the popup size is hardcoded in the package code. What do you think would be a good size from what you tested?

I might be able to give the option to configure the default popup size in the latest v3.0.0-beta version.
