### ISSUE TITLE
Sharing works only once in a PWA

### ISSUE THREAD

**Issue by rohitpal8** [nicolasbeauvais/vue-social-sharing#203]
Works fine in the browser. However, once installed as an app, the sharing happens only once. 

"Open" event is fired from the second time onwards but no sharing window is opened. This is specifically for Whatsapp.

https://stackoverflow.com/questions/61321177/vue-social-sharing-plugin-pwa-sharing-functionality-works-only-for-the-first

**Comment by nicolasbeauvais** [comment]
Hello @rohitpal8, I'm not very knowledgeable on PWA, so I do not know if any limitation is at play here. Would you mind sharing some code?
