### ISSUE TITLE
Share in Messenger

### ISSUE THREAD

**Issue by bajracharya-kshitij** [nicolasbeauvais/vue-social-sharing#204]
Hi. First of all, thank you creating this component. I want to ask if there is any option at the moment to share links to Facebook Messenger? Thanks.

**Comment by nicolasbeauvais** [comment]
Hello @bajracharya-kshitij,

according to this page: https://developers.facebook.com/docs/sharing/messenger/web there is no special link to share to Facebook Messenger, only Facebook.

Let me know if you find something!
