### ISSUE TITLE
Nuxt compatible plugin?

### ISSUE THREAD

**Issue by michaeljakob** [nicolasbeauvais/vue-social-sharing#206]
Please add a working example of how to sue vue-social-sharing on a Nuxt project.

The default example produces an error:
```
import Vue from 'vue'
  var SocialSharing = require('vue-social-sharing')
  Vue.use(SocialSharing)

// ERROR: navigator not found
```

Encapsulating the `<social-sharing>` in a `<client-only>` also does not work, even after only loading it on client mode:
```
import Vue from 'vue'
if (process.client) {
  var SocialSharing = require('vue-social-sharing')
  Vue.use(SocialSharing)
}
```

What's the correct way of adding vue-social-sharing in a Nuxt project?

**Comment by codesxt** [comment]
I addedd it by simply creating a plugin file called socialsharing.js in the plugins folder with:
```
import Vue from 'vue'
const SocialSharing = require('vue-social-sharing')

Vue.use(SocialSharing)
```
Then I imported it in nuxt.config.js by adding '~/plugins/socialsharing' to the plugins array. It's working fine for me.

**Comment by davykiala** [comment]
Hello,
I add the plugin in nuxtjs but when i run the command : npm run dev. I am getting an error  ERROR  [Vue warn]: Error in render: "ReferenceError: navigator is not defined"                19:25:21

found in

---> <SocialSharing>
I don't know why. Do you have an idea ?

**Comment by matiyin** [comment]
It's likely you forgot to load the plugin in 'client mode'.
Use this:
`plugins: [
    {
      src: '~/plugins/vue-social-sharing',
      mode: 'client'
    }
]`

**Comment by davykiala** [comment]
Thanks  @matiyin  great it's work like a charm

**Comment by nicolasbeauvais** [comment]
Thank you for raising this issue, the [latest version](https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v3.0.0-beta.2) of `Vue Social Sharing` has been released with improved support for SSR.
