### ISSUE TITLE
Image not display

### ISSUE THREAD

**Issue by MGuadalupe** [nicolasbeauvais/vue-social-sharing#207]
Hello, first of all, thank you very much for all your job, this libreary is great!

But i have a problem, when I share my article, the image doesn't display on facebook or any social media I added.

I already tried with the meta tags solution , but is not working for me.  I'm using nuxt.js and my code is something like this:

![image](https://user-images.githubusercontent.com/21975285/80988136-6ba44900-8e09-11ea-9b97-07105a966285.png)

thanks for the help!

**Comment by nicolasbeauvais** [comment]
Hello @MGuadalupe, this issue is not related to this package.
Please ask for help on the Vuejs Gitter chat room, the official Vuejs forum or StackOverflow.
