### ISSUE TITLE
Not getting props/data inside component i.e <social-sharing>

### ISSUE THREAD

**Issue by waseema93** [nicolasbeauvais/vue-social-sharing#208]
hello @nicolasbeauvais
I am using vue 2 , i am not getting props/data inside social-sharing component also tried the same code provided by you in fiddle but still same code not working..

**Comment by nicolasbeauvais** [comment]
Hello @waseema93,

please provide a non-working example of code.

**Comment by Kolobok12309** [comment]
@nicolasbeauvais i think he is about something like [this](https://jsfiddle.net/Sova12309/8xy37fgq/45/)

**Comment by waseema93** [comment]
@Kolobok12309  thanks for recreating my issue....
@nicolasbeauvais  above example suggested by @Kolobok12309  is exactly the same...kindly help

**Comment by Kolobok12309** [comment]
@waseema93 You can user comething like this, [example](https://jsfiddle.net/Sova12309/vnqyxfo8/9/)
```html
<VueSocialSharing :prop="prop">
  <network>
    {{ $attrs.prop }}
  </network>
</VueSocialSharing>
```

**Comment by nicolasbeauvais** [comment]
@waseema93 Indeed this is one of the limitation of Vue Social Sharing v2, I've been working on making it easier to work with dynamic props and templates in the v3 which should be out of beta in the following weeks. Thank you @Kolobok12309 for providing a workaround!
