### ISSUE TITLE
`$parent` doesn't work inside component

### ISSUE THREAD

**Issue by KonradDeskiewicz** [nicolasbeauvais/vue-social-sharing#212]
I'm trying to reproduce some of the steps from closed issues, but still cant access data from main component.
```vue
<network
   v-if="$parent.article.sharingRights.includes('social')"
   network="facebook"
>
  <div class="share-button mx-2">
    <fa :icon="['fab', 'facebook-f']" />
  </div>
</network>
```

Unfortunately, the only thing I got is console error
> "TypeError: Cannot read property 'sharingRights' of undefined"`

**Comment by nicolasbeauvais** [comment]
Hello @KonradDeskiewicz, did you used the `inline-template` attribute on your `vue-social-sharing` component?

Also, a v3.0.0-beta version of this package has been released and work with only one component to make it easier to use.
