### ISSUE TITLE
SMS IOS

### ISSUE THREAD

**Issue by VictorVermeulen** [nicolasbeauvais/vue-social-sharing#214]
https://github.com/nicolasbeauvais/vue-social-sharing/issues/133

I posted here but looks like its closed already. Should I update to socialsharing version 3.x to implement this even when I am not using Server Side Rendering or Vue 3.x?

**Comment by nicolasbeauvais** [comment]
I answered you in the other issue, version 3.x is compatible with vue 2.x too but it's still in beta. You can apply the fix proposed by @holygekko in vue-social-sharing v2.x if you want by overind the `sms_ios` network as explained in the Readme: https://github.com/nicolasbeauvais/vue-social-sharing/tree/17d26cce2043da6f15e75d203b3c0da3e348d3a7#extending-the-network-list

```html
<social-sharing :networks="overriddenNetworks" inline-template>
    <div>
        <network network="custom">
            Custom network
        </network>
    </div>
</social-sharing>

<script>
    new Vue({
      data: {
        overriddenNetworks: {
          "sms_ios": {
            "sharer": "sms:&body=@url%20@description",
            "type": "direct"
          },
        }
      }
    });
</script>
```
