### ISSUE TITLE
Showing what content is included in each social medium

### ISSUE THREAD

**Issue by ibrahimBeladi** [nicolasbeauvais/vue-social-sharing#215]
First off, good job, it is really time saving library.

I noticed that there is mismatch in some social media; For example:
In Telegram, it is URL then description.
While, in Twitter, it is title then URL (and hashtags and twitter-user)
It might be good to show which data are supplied by each social medium, and also show how to customize that.

Thank you for your good work! :+1:

**Comment by nicolasbeauvais** [comment]
Hello @ibrahimBeladi, thank you for raising this issue, it's indeed an inconsistency issue. I fixed it in the latest version (v3.0.0-beta.4) and updated the README documentation with detailed attributes for each networks.
