### ISSUE TITLE
2 errors - not defined

### ISSUE THREAD

**Issue by bogdanfer** [nicolasbeauvais/vue-social-sharing#216]
```
4:8  error  'VueSocialSharing' is defined but never used  no-unused-vars
6:9  error  'SocialSharing' is not defined                no-undef
```

so tried this:

```
import VueSocialSharing from "vue-social-sharing";
Vue.use(VueSocialSharing);

```
but then this: 

`vue-social-sharing.js?bd8c:1 Uncaught TypeError: Cannot read property 'networks' of undefined`

I guess there's an error after the update. Used it 2 weeks and was working perfectly.

**Comment by nicolasbeauvais** [comment]
Hello @bogdanfer, thank you for raising this issue.

I indeed failed the last beta build, it is now fixed.

It looks like you upgraded from vue-social-sharing v2 to v3 ? If that's the case take a look at the documentation as a lot of things have been changed between the two versions.
