### ISSUE TITLE
Title Prop returning duplicate Value

### ISSUE THREAD

**Issue by tayler-ramsay** [nicolasbeauvais/vue-social-sharing#217]
I am using it in a Nuxt app and I have only tried twitter network. When I set the title prop it displays twice in the tweet.

**Comment by nicolasbeauvais** [comment]
Hello @tayler-ramsay,

thank you for reporting this issue, it has been fixed in the lastest release!

**Comment by tayler-ramsay** [comment]
Thank You!
Best regards,

*Tayler Ramsay ({*
*   ({Developer} && "Designer")*
*      return {*
                   [ Phone: (717) 578-3243,
                     *www.tayler.co* <http://www.taylerramsay.com/>  *]*
*            }*
*       });*


*"It's such a fine line between stupid, and clever."*
