### ISSUE TITLE
3.0-beta requires lots of redundant code

### ISSUE THREAD

**Issue by KonradDeskiewicz** [nicolasbeauvais/vue-social-sharing#218]
is there an chance to fold all props into one alternative object `options`, that we can pass as single line and define only in one place?

Something like this:

```javascript
<ShareNetwork network="facebook" :options="sharingOptions">Share this!</ShareNetwork>

export default {
 computed: {
    sharingOptions: {
      :url="this.currentUrl",
      :title="this.article.title",
    }
  }
}
```

**Comment by nicolasbeauvais** [comment]
Hello @KonradDeskiewicz,

the whole point of the v3 refactoring was to make Vue Social Sharing more flexible while improving developer experience, but maybe the way I designed it is not as straightforward as I would have like.

For a single sharer the basic approach is less redundant:
```html
<ShareNetwork network="facebook" :url="currentUrl" :title="article.title">Share this!</ShareNetwork>
```

And a simple for loop will let you define as many sharers as you want while staying concise, as you can see in [this example](https://github.com/nicolasbeauvais/vue-social-sharing/blob/master/examples/App.vue)

Finally, if want to spread an object of properties you can use `v-bind` as [shown here](https://github.com/vuejs/vue/issues/8780#issuecomment-420099462).

Hope this answer your question and that the new approach I took with Vue Social Sharing make more sense now :smile:

**Comment by KonradDeskiewicz** [comment]
OK. Got it.
