### ISSUE TITLE
Unknown custom element: <network>

### ISSUE THREAD

**Issue by bart** [nicolasbeauvais/vue-social-sharing#22]
First of all this module looks promising to me! But when I try to use it I'm getting the following error in the Chrome developer console:

```[Vue warn]: Unknown custom element: <network> - did you register the component correctly? For recursive components, make sure to provide the "name" option.```

I created a component named 'social-sharing' and included the vue social sharing in my app.js. In my component I used the syntax from the example that resulted in the error above. Any idea?

I'm on Vue 2 and I installed vue social sharing 1.1.2 via npm. Thanks!!

**Comment by nicolasbeauvais** [comment]
Hello @bart, the readme example with the `<network>` tag is for the latest version (2.2.x).

You can see the instruction for 1.1.2 version here: https://github.com/nicolasbeauvais/vue-social-sharing/tree/78b4b1d5949933df28e931ff9695c607f7afab4a

But I can only advise you to use the latest 2.2.x version of `vue-social-sharing` :)

I updated the current readme that may have confused you https://github.com/nicolasbeauvais/vue-social-sharing/commit/dfeaa8e7144e30abe10e52fd17c7e3b988373842

**Comment by nicroto** [comment]
I am using 2.3.3 and am getting the same error in a NUXT app.

**Comment by nicroto** [comment]
@nicolasbeauvais would you care to take a look at this?

**Comment by nataliawww** [comment]
+1

**Comment by francoisauclair911** [comment]
+1
