### ISSUE TITLE
Some data not displaying in shares

### ISSUE THREAD

**Issue by Nantiee** [nicolasbeauvais/vue-social-sharing#220]
Hi,
I used your component for sharing on twitter, facebook & linkedin.
Twitter is okay.
Facebook don't use title and description I send. Quote and url are ok. Hashtags only get the first one.
Linkedin only get the url, not title or description.

All components have the same properties.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/2286536/82656380-f667af00-9c23-11ea-9024-7a578b17ce6f.png">
<img width="664" alt="image" src="https://user-images.githubusercontent.com/2286536/82656430-0c756f80-9c24-11ea-9f55-42f6340f4291.png">
<img width="607" alt="image" src="https://user-images.githubusercontent.com/2286536/82656544-3b8be100-9c24-11ea-8cb4-7444ee8cf570.png">

```
<template>
  <ul class="social">
    <li>
      <ShareNetwork
        network="twitter"
        :url="url"
        :title="title"
        :hashtags="hashtags"
        class="social__link"
      >
        <app-icon icon="twitter" />
      </ShareNetwork>
    </li>
    <li>
      <ShareNetwork
        network="facebook"
        :url="url"
        :title="title"
        :quote="title"
        :description="description"
        :hashtags="hashtags"
        class="social__link"
      >
        <app-icon icon="facebook" />
      </ShareNetwork>
    </li>
    <li>
      <ShareNetwork
        network="linkedin"
        :url="url"
        :title="title"
        :description="description"
        class="social__link"
      >
        <app-icon icon="linkedin" />
      </ShareNetwork>
    </li>
  </ul>
</template>
<script>
export default {
  props: {
    url: {
      type: String,
      required: true
    },
    title: {
      type: String,
      required: true
    },
    description: {
      type: String,
      default: null
    },
    hashtags: {
      type: String,
      default: null
    }
  }
}
</script>
```

Thanks :)

**Comment by nicolasbeauvais** [comment]
Hello @Nantiee, thank you for reporting this issue.

#### For Facebook
It looks like Facebook does not use the title and description anymore but only the data from the open-graph meta tags, and the only way to override theses is by using a different sharing link and passing an APP_ID: https://stackoverflow.com/a/24257496/3005955. For the single hashtag issue this is stated in the documentation, Facebook only accept one hashtag.

This means that we could provide two ways to share on Facebook, the regular one without the possibility to override open-graph data, and the sharing link with enforced APP_ID. What are your thoughts on this?

#### For LinkedIn
LinkedIn recently updated their sharing endpoint (April 2020) and now only the URL property can be used: https://stackoverflow.com/a/61583006/3005955. I updated the documentation accordingly

And a small unrelated tip, you can use a v-for loop to avoid having to write all share network one by one in your HTML, see an example here: https://github.com/nicolasbeauvais/vue-social-sharing/blob/master/examples/App.vue

**Comment by Nantiee** [comment]
Hello,

This will be explained to the PM and client.

I changed code with loop, this is clearly better !

Thank for your answer :)
