### ISSUE TITLE
all share buttons  not work

### ISSUE THREAD

**Issue by mShbieb** [nicolasbeauvais/vue-social-sharing#222]
Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "url"

**Comment by mShbieb** [comment]
[https://prnt.sc/smdjjp](url)

**Comment by nicolasbeauvais** [comment]
Hello @mShbieb, this look like a problem on your end. As you can see on the demo website https://nicolasbeauvais.github.io/vue-social-sharing/?path=/story/vuesocialsharing--multiple-share-networks the share buttons works fine without this error.

Please share more of your code, ideally by reproducing the bug on https://jsfiddle.net/ or a similar tool.

**Comment by mShbieb** [comment]
I found the problem just in url prop name, i chenged it to outher name (url to link) and it work

**Comment by nicolasbeauvais** [comment]
Great!
