### ISSUE TITLE
Can you add Yammer as network ?

### ISSUE THREAD

**Issue by ChoOo7** [nicolasbeauvais/vue-social-sharing#223]
Can you add Yammer as network ?

Thanks

**Comment by nicolasbeauvais** [comment]
Hello @ChoOo7,

I do not have a Yammer account to make tests, could you confirm that the following sharing link works?

`https://www.yammer.com/messages/new?login=true&trk_event=yammer_share&status=test%20vue%20social%20sharing%20https%3A%2F%2Fvuejs.org%2F` 

and 

`https://www.yammer.com/messages/new?status=test%20vue%20social%20sharing%20https%3A%2F%2Fvuejs.org%2F`

**Comment by ChoOo7** [comment]
Both are Ok, thanks  :)

**Comment by nicolasbeauvais** [comment]
@ChoOo7 Yammer has been included in the latest release :smiley:
