### ISSUE TITLE
Some dark mode ?

### ISSUE THREAD

**Issue by Epistol** [nicolasbeauvais/vue-social-sharing#226]
Could it be possible to get a dark mode ? Or at least a possibility to remove the background of the icons to set the one we'd like to be put ?

**Comment by nicolasbeauvais** [comment]
Hello @Epistol, this package only provide a [renderless component](https://github.com/nicolasbeauvais/vue-social-sharing#what-is-a-renderless-component) you are free to set any style to the sharing buttons.
