### ISSUE TITLE
[docs] Change the way of listing the properies of networks and the networks

### ISSUE THREAD

**Issue by ibrahimBeladi** [nicolasbeauvais/vue-social-sharing#227]
I am thinking of changing the networks and their properties section in readme file into more scannable and more comparable and into fewer tables.

First, bring back the properties table from around beta-3:
Prop           | Data Type  | Default   | Description
-------------- | ---------- | --------- | -----------
`url`          | String     | current page's URL   | URL to share.
`title`        | String     |           | Sharing title (when available).
`description`  | String     |           | Sharing description (when available).
... | ... | ... | ... 

and secondly make a long table that contains the networks as rows and properties as columns:
Network           | `url`  | `title`   | `description` | ... | Extras
-------------- | :----------: | :---------: | :-----------:  | -----------  | ------
Facebook          | :heavy_check_mark:      | :heavy_check_mark:   | :heavy_check_mark:  | ... |  `hashtags` A list of comma-separated hashtags, only the first one will used. <br/> `quote` Facebook quote.
Twitter          | :heavy_check_mark:      | :heavy_check_mark:   | :x:  | ... |  `hashtags` A list of comma-separated hashtags. <br/> `twitter-user` Twitter user to mention.
... | ... | ... | ...   | ... | 

If you accept this idea I can do it.

**Comment by nicolasbeauvais** [comment]
Hello @ibrahimBeladi,

This is indeed a good idea and would make things more readable. The reasoning behind having a table for each network is that some of them, like WhatsApp, only allow sharing a single text string, so Vue Social Sharing concatenate several fields (title, url, description) into one which I consider as a non default behavior that should be clearly stated in the documentation, while other networks like Facebook have 3 distinct parameters. So if you have any idea on how to improve this part of the documentation I would gladly appreciate it.

The `extras` column is a good idea to keep the table small.

You can create a PR for this, it will be a good improvement :+1:

**Comment by ibrahimBeladi** [comment]
Might change `Extras` into `Extras/Comments` to solve that. And add a comment for WhatsApp mentioning that point.

Will submit a PR in the following days.

**Comment by nicolasbeauvais** [comment]
It's the case for:

- Line
- Skype
- SMS
- Telegram
- Viber
- WhatsApp
- Yammer

All share a string concatenated like that `"$title $url $description"`
