### ISSUE TITLE
Unknown custom element: <ShareNetwork> - did you register the component correctly? 

### ISSUE THREAD

**Issue by zahidul1994** [nicolasbeauvais/vue-social-sharing#229]
when i use my vue component that show in error

**Comment by nicolasbeauvais** [comment]
Hello @zahidul1994,

did you load the library as explained in the Readme ?

https://github.com/nicolasbeauvais/vue-social-sharing#loading-the-library

If so please share some code to help me debug your issue, but it's likely due to your usage and not the library itself.

**Comment by cecurin** [comment]
Hi there, I'm having the same problem in Nuxt. I copied the code in nuxt.config, and also copied the example code to know if works, but it isn't. Is there something else that we are missing?

```
[Vue warn]: Unknown custom element: <ShareNetwork> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <ModalShare>
       <Pages/blog/Id.vue> at pages/blog/_id.vue
         <Nuxt>
           <Layouts/default.vue> at layouts/default.vue
             <Root>
```

**Comment by shahabgohar** [comment]
any progress soo far !!

**Comment by shahabgohar** [comment]
`<div class="content">
        <SocialSharing
          network="twitter"
          url="https://news.vuejs.org/issues/180"
          title="Say hi to Vite! A brand new, extremely fast development setup for Vue."
          description="This week, I’d like to introduce you to 'Vite', which means 'Fast'. It’s a brand new development setup created by Evan You."
          quote="The hot reload is so fast it\'s near instant. - Evan You"
          hashtags="vuejs,vite,javascript"
          twitterUser="youyuxi"
        >
          <div>
            facebook
          </div>
        </SocialSharing>
      </div>`

**Comment by shahabgohar** [comment]
and it is in nuxt

**Comment by carolinecblaker** [comment]
I'm also having this issue using WebPack
`Unknown custom element: <sharenetwork> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

webpack.config.js //added for troubleshooting
`const VueSocialSharing = require('vue-social-sharing')`

index.js:
`var share= new Vue({
    el:'#sharing',
    data:{sharing: {
        url: 'https://news.vuejs.org/issues/180',
        title: 'Say hi to Vite! A brand new, extremely fast development setup for Vue.',
        description: 'This week, I’d like to introduce you to "Vite", which means "Fast". It’s a brand new development setup created by Evan You.',
        quote: 'The hot reload is so fast it\'s near instant. - Evan You',
        hashtags: 'vuejs,vite,javascript',
        twitterUser: 'youyuxi'
      },
      networks: [
        { network: 'baidu', name: 'Baidu', icon: 'fas fah fa-lg fa-paw', color: '#2529d8' },
        { network: 'buffer', name: 'Buffer', icon: 'fab fah fa-lg fa-buffer', color: '#323b43' },
        { network: 'email', name: 'Email', icon: 'far fah fa-lg fa-envelope', color: '#333333' },
        { network: 'evernote', name: 'Evernote', icon: 'fab fah fa-lg fa-evernote', color: '#2dbe60' },
        { network: 'facebook', name: 'Facebook', icon: 'fab fah fa-lg fa-facebook-f', color: '#1877f2' },
        { network: 'flipboard', name: 'Flipboard', icon: 'fab fah fa-lg fa-flipboard', color: '#e12828' },
        { network: 'hackernews', name: 'HackerNews', icon: 'fab fah fa-lg fa-hacker-news', color: '#ff4000' },
        { network: 'instapaper', name: 'Instapaper', icon: 'fas fah fa-lg fa-italic', color: '#428bca' },
        { network: 'line', name: 'Line', icon: 'fab fah fa-lg fa-line', color: '#00c300' },
        { network: 'linkedin', name: 'LinkedIn', icon: 'fab fah fa-lg fa-linkedin', color: '#007bb5' },
        { network: 'odnoklassniki', name: 'Odnoklassniki', icon: 'fab fah fa-lg fa-odnoklassniki', color: '#ed812b' },
        { network: 'pinterest', name: 'Pinterest', icon: 'fab fah fa-lg fa-pinterest', color: '#bd081c' },
        { network: 'pocket', name: 'Pocket', icon: 'fab fah fa-lg fa-get-pocket', color: '#ef4056' },
        { network: 'quora', name: 'Quora', icon: 'fab fah fa-lg fa-quora', color: '#a82400' },
        { network: 'reddit', name: 'Reddit', icon: 'fab fah fa-lg fa-reddit-alien', color: '#ff4500' },
        { network: 'skype', name: 'Skype', icon: 'fab fah fa-lg fa-skype', color: '#00aff0' },
        { network: 'sms', name: 'SMS', icon: 'far fah fa-lg fa-comment-dots', color: '#333333' },
        { network: 'stumbleupon', name: 'StumbleUpon', icon: 'fab fah fa-lg fa-stumbleupon', color: '#eb4924' },
        { network: 'telegram', name: 'Telegram', icon: 'fab fah fa-lg fa-telegram-plane', color: '#0088cc' },
        { network: 'tumblr', name: 'Tumblr', icon: 'fab fah fa-lg fa-tumblr', color: '#35465c' },
        { network: 'twitter', name: 'Twitter', icon: 'fab fah fa-lg fa-twitter', color: '#1da1f2' },
        { network: 'viber', name: 'Viber', icon: 'fab fah fa-lg fa-viber', color: '#59267c' },
        { network: 'vk', name: 'Vk', icon: 'fab fah fa-lg fa-vk', color: '#4a76a8' },
        { network: 'weibo', name: 'Weibo', icon: 'fab fah fa-lg fa-weibo', color: '#e9152d' },
        { network: 'whatsapp', name: 'Whatsapp', icon: 'fab fah fa-lg fa-whatsapp', color: '#25d366' },
        { network: 'wordpress', name: 'Wordpress', icon: 'fab fah fa-lg fa-wordpress', color: '#21759b' },
        { network: 'xing', name: 'Xing', icon: 'fab fah fa-lg fa-xing', color: '#026466' },
        { network: 'yammer', name: 'Yammer', icon: 'fab fah fa-lg fa-yammer', color: '#0072c6' }
      ],
        showSharing:false
        
    },
    
    
});`


App HTML:
`<ShareNetwork
        v-for="network in networks"
        :network="network.network"
        :key="network.network"
        :style="{backgroundColor: network.color}"
        :url="sharing.url"
        :title="sharing.title"
        :description="sharing.description"
        :quote="sharing.quote"
        :hashtags="sharing.hashtags"
        :twitterUser="sharing.twitterUser"
      >
        <i :class="network.icon"></i>
        <span>{{ network.name }}</span>
      </ShareNetwork>
`

**Comment by shahabgohar** [comment]
I solve my issue by local import in my nuxt app and i think the documentation is kind of miss guiding developers

`import { ShareNetwork } from '../node_modules/vue-social-sharing/dist/vue-social-sharing'
  components: {
    ShareNetwork
  },
`

**Comment by alvarosaburido** [comment]
> Hi there, I'm having the same problem in Nuxt. I copied the code in nuxt.config, and also copied the example code to know if works, but it isn't. Is there something else that we are missing?
> 
> ```
> [Vue warn]: Unknown custom element: <ShareNetwork> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
> 
> found in
> 
> ---> <ModalShare>
>        <Pages/blog/Id.vue> at pages/blog/_id.vue
>          <Nuxt>
>            <Layouts/default.vue> at layouts/default.vue
>              <Root>
> ```

Same problem here, also `Error: Cannot find module 'vue-social-sharing/nuxt'` if I add it only in `nuxt.config.js`

**Comment by zeflq** [comment]
you have to add it as plugin;
**vue-social-sharing.js**
`import Vue from 'vue'
const VueSocialSharing = require('vue-social-sharing')
Vue.use(VueSocialSharing)`

**nuxt.config.js**
```
plugins: [
...
'~/plugins/vue-social-sharing.js',
]
```

**Comment by knownamenow** [comment]
i solve this problem in nuxt

`modules: [
   ...
    'vue-social-sharing/nuxt',
  ...
  ],`

in vue template

`
	<ShareNetwork
											network="facebook"
											url="https://news.vuejs.org/issues/180"
											title="Say hi to Vite! A brand new, extremely fast development setup for Vue."
											description="This week, I’d like to introduce you to 'Vite', which means 'Fast'. It’s a brand new development setup created by Evan You."
											quote="The hot reload is so fast it\'s near instant. - Evan You"
											hashtags="vuejs,vite"
										>Share on Facebook</ShareNetwork>
`

**Comment by nicolasbeauvais** [comment]
Thank you @zeflq and @knownamenow for the solution!

**Comment by praditha-hidayat** [comment]
Thanks @knownamenow 
Your solutions is working

**Comment by keithpaul** [comment]
Have the same problem on a normal vue 3 project (NOT NUXT).

<template>
<ShareNetwork>
.....
</ShareNetwork>
</template>

<script>
import Vue from 'vue'
const VueSocialSharing = require('vue-social-sharing')
Vue.use(VueSocialSharing)

export default {
...
}
</script>

Throws error 'Cannot read property 'use' of undefined'

**Comment by jamiesoncj** [comment]
In case this helps anyone. I was trying to load the library directly in HTML (not using Webpack or Nuxt etc.)

To get it to work, I needed to  do the following:

```javascript
// import vue
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>

// import vue-social-sharing
<script src="https://unpkg.com/vue-social-sharing@3.0.8/dist/vue-social-sharing.js"></script>

<script>
  Vue.use(VueSocialSharing.default); // NB: .default is important
  var app = new Vue({
    el: "#app",
    data: {},
  });
</script>
```

Then in the HTML you can use the library with
```html
<!-- NB: share-network NOT ShareNetwork -->
<share-network
  network="facebook"
  url="https://news.vuejs.org/issues/180"
  title="Say hi to Vite! A brand new, extremely fast development setup for Vue."
  description="This week, I’d like to introduce you to 'Vite', which means 'Fast'. It’s a brand new development setup created by Evan You."
  quote="The hot reload is so fast it\'s near instant. - Evan You"
  hashtags="vuejs,vite"
>
  Share on Facebook
</share-network>
```
