### ISSUE TITLE
Some remarks and/or optimization tips

### ISSUE THREAD

**Issue by pimlie** [nicolasbeauvais/vue-social-sharing#230]
Hey, thanks for your awesome work on this component! Have been using this component for some time but have for the moment switched to a local fork, would like to explain my reasons for that by giving some (optimization) tips:

- The file `src/networks.js` should export individual variables. Then eg in the Nuxt.js plugin you can make it configurable which networks should be included in the build and all other networks can be tree-shaked.
- Remove the default import of all networks, if I dont use hackernews on my page then I shouldnt need to include the 49 bytes for the hackernews share url.
- Add a sideEffect mention in package.json to mark the share-network component as having side effects
- It would be nice if using events was injected into the component some how instead of being embedded. That way it could be removed by a build parameter, eg I dont need it and it only increases the size unnecessarily
- Even more, if you dont use events then the ShareNetwork component could be functional which is much faster to render with Vue2 (this is because keeping a reference to the popup window is the only thing you cannot easily do in a functional component)
- Currently v3 also contains a potential memory leak because the interval doesn't get cleared when the component is destroyed. So if you have a share popup open and navigate to another page, then the interval will keep the share-network component from being destroyed. It should still be cleared once you close the popup though, but that could lead to unexpected behaviour if you are emitting events on a component that has been removed already
- It would be nice if you could still locally override the network link by passing a link prop, currently that is not possible
- A tiny optimization feature, navigator.userAgent wont change after bundle load. So it could be moved outside of any component method, but also you only need it for the sms key so if you dont use sms it doesnt need to check the useragent.
- You could move all 7 replace calls into a single one, which should improve perf a little bit as you dont need to create 7 new strings. You could use a single replace method by using a function callback: `link.replace(/@(tu|u|t..)/, (m) => if (m === 'tu') return this.twitterUser ..etc`
- Instead of opening a popup when 'touched', you could create an inline link tag and just call click on that: `const link = document.createElement('a'); link.href = shareLink; link.click()`. 

Let me know if I can help you with anything of the above. I didnt make a PR because some changes could be subject to personal preference, but would be happy to do so :)

**Comment by nicolasbeauvais** [comment]
Hello @pimlie,

thank you for the deep dive, this is totally in the spirit of this package, I love it.

Feel free to implement these changes, ideally one PR for each. Some of them would need a major release, so start with the non-breaking ones.

I can implement some of them if you do not have the time, keep me updated!
