### ISSUE TITLE
Twitter - Missing image meta

### ISSUE THREAD

**Issue by shide1989** [nicolasbeauvais/vue-social-sharing#231]
hey there,

the meta "twitter:image"" is missing from the vus-social-sharing Twitter network : 
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary

**Comment by nicolasbeauvais** [comment]
Hello @shide1989,

as explained in the Readme.md [Understanding social sharing
](https://github.com/nicolasbeauvais/vue-social-sharing#understanding-social-sharing) section, you must implement Open Graph meta tags by yourself.
