### ISSUE TITLE
Does this use font awesome by default?

### ISSUE THREAD

**Issue by Derockypeter** [nicolasbeauvais/vue-social-sharing#232]
I am trying this on my vue project but it only shows plain text without styling, do I need to style it. Thanks

**Comment by nicolasbeauvais** [comment]
Hello @Derockypeter, this package only provide a [renderless component](https://github.com/nicolasbeauvais/vue-social-sharing#what-is-a-renderless-component) you are free to use fontawesome or any other library to style the sharing buttons.
