### ISSUE TITLE
Unknown custom element: <ShareNetwork> 

### ISSUE THREAD

**Issue by gogs85** [nicolasbeauvais/vue-social-sharing#233]
: Unknown custom element: <ShareNetwork> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
How to solve this?

main.js
`import VueSocialSharing from 'vue-social-sharing';
Vue.use(
  VueSocialSharing,
  );
`
and in component

` <ShareNetwork
      network="twitter"
      url="https://news.vuejs.org/issues/180"
      title="Say hi to Vite! A brand new, extremely fast development setup for Vue."
      description="This week, I’d like to introduce you to 'Vite', which means 'Fast'. It’s a brand new development setup created by Evan You."
      quote="The hot reload is so fast it\'s near instant. - Evan You"
      hashtags="vuejs,vite,javascript"
      twitterUser="youyuxi"
    >
    <i class="fab fah fa-lg fa-twitter"></i>
    <span>Share on Twitter</span>
  </ShareNetwork>`

**Comment by SkiperX** [comment]
share-network in template, not ShareNetwork

**Comment by macoram** [comment]
I am getting the same error even using share-network in the template

**Comment by rhyswfbowles** [comment]
Hi @macoram and @gogs85 - I'm struggling to replicate this issue. I've mocked up an example here: https://codesandbox.io/s/pensive-glade-7rs3k

Have you registered your main.js in the order as seen in this example?

**Comment by lianee** [comment]
Without using a packager and import, the component ShareNetwork is not exported: [fiddle](https://jsfiddle.net/Liane/c7zn1vyb/)

**Comment by lianee** [comment]
Issue still there in 3.0.3, is there anything we can do to use this right in the browser?
