### ISSUE TITLE
Telegram Sharing - DESKOP - not working

### ISSUE THREAD

**Issue by Roby-iTuna** [nicolasbeauvais/vue-social-sharing#234]
Hi,
i'm just used this wonderful plugin and i noticed that TELEGRAM sharing not works on desktop with "telegram web".

WHATS EXPECTED:
Share content on Telegram

HOW TO REPLICATE ISSUE: 
You can try directly from documentation DEMO page: https://nicolasbeauvais.github.io/vue-social-sharing/?path=/story/vuesocialsharing--multiple-share-networks

ISSUE:
Clicking on Telegram Sharing link opens a new window showing all data set and ready to go.
If you try to click on "Share" green button, nothing happens.

BROWSER: 
Chrome (Ubuntu 20.04 - last ver.)

**Comment by rhyswfbowles** [comment]
Hi Roby, 

Just taking a look at the Telegram popup, it looks like the share URL is an application specific one (https://coderwall.com/p/mtjaeq/ios-custom-url-scheme)

If you hover over the share button it looks like it is trying to directly open a Telegram app on a device `tg://`.

This is something on telegrams side, not this packages

**Comment by nicolasbeauvais** [comment]
Thank you @rhyswfbowles for the explanation, if we can do something about this @Roby-iTuna, feel free to re-open this issue.
