### ISSUE TITLE
Permission denied to access property "__ob__" on cross-origin object

### ISSUE THREAD

**Issue by NikolayMurha** [nicolasbeauvais/vue-social-sharing#235]
Hello.

On the page https://nicolasbeauvais.github.io/vue-social-sharing/?path=/story/vuesocialsharing--multiple-share-networks
when I click to any share button and click to other without close previous popup I have error
"Permission denied to access property "__ob__" on cross-origin object"
I have the same problem in my project.

As I understood, the problem with [window.open](https://github.com/nicolasbeauvais/vue-social-sharing/blob/master/src/share-network.js#L216) function. Differrent buttons use same window name, but since each button has its own 'this.popup', there is no way to use the existing window.

I see two possible solutions:
1. Use  uniq window name for different networks/buttons.
2. Store popup to common variable and use across components (e.g. $window._socialSharingPopup)

**Comment by hansfelix** [comment]
@nicolasbeauvais I sent a PR where I set a window name for each social share button. If you want you could assigne me

**Comment by nicolasbeauvais** [comment]
Hello @NikolayMurha, this bug is now fixed in the latest release (v3.0.2) thanks to @hansfelix's PR #244 !
