### ISSUE TITLE
facebook share with image is not working ?

### ISSUE THREAD

**Issue by kuldeepgh** [nicolasbeauvais/vue-social-sharing#236]
i tried a lot . i am using vue-meta as well but its not working

**Comment by allaghi** [comment]
Same issue.

**Comment by nicolasbeauvais** [comment]
Hello @kuldeepgh and @allaghi,

as explained in the Readme.md [Understanding social sharing](https://github.com/nicolasbeauvais/vue-social-sharing#understanding-social-sharing) section, you must implement Open Graph meta tags by yourself.

You can see on this library examples that it works correctly so it is likely to be an error in your implementation of Open Graph meta tags.

[This tool from Facebook](https://developers.facebook.com/tools/debug/) can help you set up your tags.
