### ISSUE TITLE
[Bug] Only the first hashtag is included (Facebook)

### ISSUE THREAD

**Issue by AbdallahAlhaddad** [nicolasbeauvais/vue-social-sharing#237]
First of all I want to thank you for the awesome component.

I've noticed that only one hashtag is added when trying to share on Facebook.

The problem can be reproduced on your [multiple-share-networks](https://nicolasbeauvais.github.io/vue-social-sharing/?path=/story/vuesocialsharing--multiple-share-networks) demo.

**Comment by adrielwerlich** [comment]
yes... I´m getting the same issue. Only the first hash tag is being included in facebook. I´ve tested in linkedin, and no hashtags are showing... Is there a fix to this already? This is great component

**Comment by nicolasbeauvais** [comment]
Hello @AbdallahAlhaddad and @adrielwerlich, this is a limitation imposed by Facebook, it's written in the documentation that only one hashtag can be shared on Facebook. There's nothing we can do about it.
