### ISSUE TITLE
Facebook Send button

### ISSUE THREAD

**Issue by bigbadwoolfe** [nicolasbeauvais/vue-social-sharing#24]
Facebook (being the main social media outlet) has many ways to share. One of the many is via a SEND button - https://developers.facebook.com/docs/plugins/send-button

This way a link can be shared directly with a friend.

Would be nice if this came out of the box with the plugin.

Good work with this so far btw, very useful.

**Comment by nicolasbeauvais** [comment]
Hello @bigbadwoolfe, thank you for your proposition.

Implementing the Facebook send button by default in `vue-social-sharing` seems a little heavy (loading the external dependencies...) for something that will not benefit everybody.

But you can easily use it on your own:

```html
<!-- Load Facebook SDK for JavaScript -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<social-sharing url="https://vuejs.org/" inline-template>
  <div>
      <!-- Your send button code -->
      <div class="fb-send" 
        data-href="http://www.your-domain.com/your-page.html" 
       data-layout="button_count">
      </div>

      <network network="twitter">
        <i class="fa fa-twitter"></i> Twitter
      </network>
  </div>
</social-sharing>
```

Would that solution fit your needs?

**Comment by nicolasbeauvais** [comment]
Closing for now, feel free to reopen if you find something

**Comment by tmorehouse** [comment]
I know when I use the facebook share.php in websites that I have created, I get the option to share: on my timeline, a friends timeline, a page I manage or send via message.
