### ISSUE TITLE
Can you apply new prop to customize of popup window ex. Height, Width? 

### ISSUE THREAD

**Issue by akegvd** [nicolasbeauvais/vue-social-sharing#240]
I need prop to customize of popup window because for Line share.
**The default height is not enough to see Line submit button** on popup window is opened.
And **need to drag to increase height** of pop up window see that button like image I attach.
![image](https://user-images.githubusercontent.com/29142066/92910637-6d82b680-f452-11ea-84ad-613cd3e3513f.png)
![image](https://user-images.githubusercontent.com/29142066/92910701-825f4a00-f452-11ea-891f-aa03afd4b509.png)

For now I saw it's fix value **436px** in data on `social-sharing.js`

```
popup: {
  status: false,
  resizable: true,
  toolbar: false,
  menubar: false,
  scrollbars: false,
  location: false,
  directories: false,
  width: 626,
  height: 436,
  top: 0,
  left: 0,
  window: undefined,
  interval: null
}
```

**Comment by nicolasbeauvais** [comment]
Hello @akegvd,

@CarinaChenot made a PR #243 to add popup height and width customization.

Use of this feature is [documented in the readme](https://github.com/nicolasbeauvais/vue-social-sharing#customizing-the-popup-window-size).
