### ISSUE TITLE
XING share URL must be adapted

### ISSUE THREAD

**Issue by PeterSchoell** [nicolasbeauvais/vue-social-sharing#249]
XING share URL must be adapted

For example (the current link)
https://www.xing.com/app/user?op=share&url=https://www.npmjs.com/package/vue-social-sharing

Should look like: 
https://www.xing.com/social/share/spi?url=https://www.npmjs.com/package/vue-social-sharing

See also: https://dev.xing.com/plugins/share_button/docs

**Comment by nicolasbeauvais** [comment]
Hello @PeterSchoell,

Thank you for raising the issue, a fix made by @talkor has been tagged in the [latest version](https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v3.0.3).
