### ISSUE TITLE
Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by Ismaaa** [nicolasbeauvais/vue-social-sharing#25]
I'm getting this error when clicking on the share button.

It works but it throws this error..

My dependencies:
`
  "devDependencies": {
    "bootstrap-vue": "^0.16.1",
    "element-theme-default": "^1.3.4",
    "element-ui": "^1.2.8",
    "laravel-mix": "^0.8.3",
    "moment": "^2.18.1",
    "vue": "^2.1.10",
    "vue-blu": "^0.1.9",
    "vue-cookie-law": "^1.0.2",
    "vue-progressbar": "^0.7.1",
    "vue-resource": "^1.3.1",
    "vue-router": "^2.4.0",
    "vue-social-sharing": "^2.*",
    "vuex": "^2.2.1"
  }
`

![image](https://cloud.githubusercontent.com/assets/22240843/26430485/dfb0c60a-40ed-11e7-92c2-9c4ec0b8601a.png)

As i said, it still works but it throws this strange error, i tryied to update my dependencies but im still having the same error...

Thanks for you help!

**Comment by nicolasbeauvais** [comment]
Hello @Ismaaa,

Are you sure that this error comes from `vue-social-sharing`?
There is no `extend` property anywhere in the code.

Could you check the file at the line pointed in the console error (app.js:12257:15) to verify where the error come from?

Or provide a https://jsfiddle.net/ test that fails or something that can help get me started to debug this

**Comment by Ismaaa** [comment]
The error comes from:
![image](https://cloud.githubusercontent.com/assets/22240843/26497696/a70685c0-422c-11e7-94ac-6fd67f32619f.png)
All right, i'll try to reproduce this on jsfiddle

**Comment by Ismaaa** [comment]
Fixed! It was a problem with VueRouter

**Comment by ideal-life-generator** [comment]
How?

**Comment by Ismaaa** [comment]
Paste your router.js file here

**Comment by MaherSaleem** [comment]
How??
