### ISSUE TITLE
Displaying an image in Twitter tweet

### ISSUE THREAD

**Issue by somaria** [nicolasbeauvais/vue-social-sharing#251]
How can I display an image in a Twitter tweet, is there an option?

**Comment by nicolasbeauvais** [comment]
Hello @somaria, 

to display an image in a Tweet you need to share a link containing open-graph meta tags, it is explained in the [understanding social sharing](https://github.com/nicolasbeauvais/vue-social-sharing#understanding-social-sharing) section of the Readme.
