### ISSUE TITLE
Migrate SocialSharing.methods.share to 3.0.0

### ISSUE THREAD

**Issue by awronski** [nicolasbeauvais/vue-social-sharing#252]
Hi!

I use SocialSharing with nuxt.js. I call Google Analitics when sharing like this

plugins/social.js:
```js
import Vue from 'vue'
import SocialSharing from 'vue-social-sharing'
import { gaLogSocial } from '~utils/GaUtils'

SocialSharing.methods.share = function (network) {

  gaLogSocial(network, this.url)

  this.openSharer(network, this.createSharingUrl(network))
  this.$root.$emit('social_shares_open', network, this.url)
}

Vue.use(SocialSharing)
```

But when migrating to new realease 3.0.3 it stoped working:
`Cannot set property 'share' of undefined`

How to migrate it?

Thanks,

**Comment by nicolasbeauvais** [comment]
Hello @awronski,

I do not have the time to work on Vue 3 compatibility yet. Please feel free to open a PR if you need this quickly.

Thank you.
