### ISSUE TITLE
facebook share produces error

### ISSUE THREAD

**Issue by rtuttlecoder** [nicolasbeauvais/vue-social-sharing#254]
When using this for Facebook share and supplying only the title, URL, and description I am constantly getting this error message: "Parameter 'href' should represent a valid URL"

**Comment by vickyhrmawan** [comment]
> When using this for Facebook share and supplying only the title, URL, and description I am constantly getting this error message: "Parameter 'href' should represent a valid URL"

Did you put the correct url? Because this also happened to me when I did in localhost.
