### ISSUE TITLE
Can you add Teams as network ?

### ISSUE THREAD

**Issue by ChoOo7** [nicolasbeauvais/vue-social-sharing#255]
Can you add Teams as new network ?

Here the documentation : 
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams
https://docs.microsoft.com/fr-fr/microsoftteams/platform/concepts/build-and-test/share-to-teams

**Comment by nicolasbeauvais** [comment]
Hello @ChoOo7,

my time is quite limited right now, if you need this quickly please submit a pull request.

Thank you.
