### ISSUE TITLE
Using with nuxt.js - The client-side rendered virtual DOM tree is not matching server-rendered content.

### ISSUE THREAD

**Issue by awronski** [nicolasbeauvais/vue-social-sharing#26]
Hi!

My configuration:
nuxt.config.js:
```javascript
  plugins: [
    { src: '~plugins/social.js', ssr: false },
  ],
```

social.js:
```javascript
import Vue from 'vue'
import SocialSharing from 'vue-social-sharing'

Vue.use(SocialSharing)
```

And then in a .vue file pasted ```<social-sharing url="https://vuejs.org/" inline-template>[...]```

When entering the page I get on the console:
```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render. 
```

I understand the error but don't know how to fix it.

**Comment by nicolasbeauvais** [comment]
Hello @awronski,

I never tried `vue-social-sharing` with nuxt.js. But it works well on classic SSR so there is no reason that it shouldn't work with nuxt.

Could you give me more lines of your vue file so that I can replicate the bug?

**Comment by awronski** [comment]
@nicolasbeauvais Thanks for fast reply.

Here is the demo:
https://nuxt-social-sharing.glitch.me/

open console to check the error

**Comment by nicolasbeauvais** [comment]
I created a blank nuxt app using https://github.com/nuxt/starter

here is the config:
```javascript
module.exports = {
  loading: false,
  plugins: ['plugins/toto'],
  build: {
    vendor: ['vue-social-sharing']
  },

  head: {
    //
  }
}
```

content of `vue-social-sharing.js` in the `plugins` directory:
```javascript
import Vue from 'vue'
import SocialSharing from 'vue-social-sharing'

Vue.use(SocialSharing)
```

content of my `index.vue` file:
```vue
<template>
  <section class="container">
    <div>
      <social-sharing url="https://vuejs.org/" inline-template>
        <div>
          <network network="facebook">
            <i class="fa fa-facebook"></i> Facebook
          </network>
          <network network="googleplus">
            <i class="fa fa-google-plus"></i> Google +
          </network>
          
          <!-- and the others networs tag pasted from the readm.md -->
        </div>
      </social-sharing>
    </div>
  </section>
</template>

<script>
// Empty
</script>
```

And everything works great without any warning :angel: Are you sure that this is coming from `vue-social-sharing` ?

**Comment by awronski** [comment]
Hi There!

Thanks for your help, the problem was configuration.

I had:
```
  plugins: [
    { src: '~plugins/social.js', ssr: false }
  ],
```

And it should be:
```
  plugins: [
    { src: '~plugins/social.js', ssr: true }
  ],
```

**ssr: true**

or just ```plugins: ['plugins/social.js'],```


Once again thanks fot help!

**Comment by nicolasbeauvais** [comment]
Thank you too, this will probably be usefull for other users :)

**Comment by maverickpravin** [comment]
You could try wrapping the component with <no-ssr/>, or moving all dom manipulations to the mounted lifecycle hook.
