### ISSUE TITLE
Can you add Sharing to Messenger directly as a Network?

### ISSUE THREAD

**Issue by Angel-Diadraw** [nicolasbeauvais/vue-social-sharing#260]

**Comment by nicolasbeauvais** [comment]
I would accept a PR for this.

**Comment by oussj** [comment]
Hello 
I'd be happy to do it. 
I looked and found that it will however work only on mobile (see [here](https://developers.facebook.com/docs/sharing/messenger/web/)). If that's ok, I'll do the PR even if it works only on mobile

**Comment by oussj** [comment]
Hello @nicolasbeauvais 
Are you ok with my PR ?

**Comment by nicolasbeauvais** [comment]
It's merged and tagged, thank you @oussj !
