### ISSUE TITLE
Linkedin share url not working on mobile (solution in the post) - msg "this feature is available only in the linkedin app"

### ISSUE THREAD

**Issue by NoRabbit** [nicolasbeauvais/vue-social-sharing#261]
Looks like the url for sharing a page on linkedin is not supported on mobile. It gives a "this feature is available only in the linkedin app" error.
The current one works on desktop but not on mobile: 'https://www.linkedin.com/sharing/share-offsite/?url=@u' 
This one works everywhere: 'https://www.linkedin.com/shareArticle?url=@u'

**Comment by nicolasbeauvais** [comment]
Thank you @NoRabbit,

the link has been fixed in the latest release!
