### ISSUE TITLE
Page is refreshing while sharing facebook and linkedin

### ISSUE THREAD

**Issue by saimunhossain** [nicolasbeauvais/vue-social-sharing#263]

**Comment by nicolasbeauvais** [comment]
Hello @saimunhossain,

could you provide a piece of code showing the code using fiddle or something similar ?

I could not replicate.

Thank you.

**Comment by MartinsOnuoha** [comment]
@nicolasbeauvais I have this same error, the page refreshes once a network is selected, I don't know if this is a browser behavior. and I'm not sure how to prevent it using one of the events. I'm using this with Quasar.
```javascript
// ./boot/socialSharing.js

import SocialMediaShare from 'vue-social-sharing';

export default async ({ Vue }) => {
  Vue.use(SocialMediaShare);
};

```

I have a SocialShare.vue file

```html
           <!-- SocialShare.vue -->
            <div class="share-item" v-for="(channel, i) in channels" :key="i">
                <ShareNetwork
                  :network="channel.network"
                  :url="shareUrl"
                  title="...."
                  description="...."
                  quote="..."
                  hashtags="isabisport,bmgames"
                >
                  <div>
                    <img height="36" :src="channel.icon" alt="" /> <br />
                    <div class="">{{ channel.network }}</div>
                  </div>
                </ShareNetwork>
              </div>
```

when an option is selected and a new browser window pops up, the application redirects to the base url

**Comment by pdapnz** [comment]
I'm run into same issue with all types of shares. This is probably happens if you use Vue router in `history` mode.

https://github.com/nicolasbeauvais/vue-social-sharing/blob/e39fd9bcf8b5b9f8a1bf09fca35a9cb4d94eee4c/src/share-network.js#L190

Problem should be solved by replacing `href` attribbute from `#` to `javascript:void(0)`.

**Comment by nicolasbeauvais** [comment]
Hello, thanks to @pdapnz this issue is now fixed in the latest release !
