### ISSUE TITLE
Spaces in hashtag

### ISSUE THREAD

**Issue by yaeru** [nicolasbeauvais/vue-social-sharing#268]
Hi! Great plugin. When I want to share the name of my articles as a hashtag, it works great, except that if the name is of several words it does not combine them and only the first word is a hashtag.
Is there an option to remove the spaces?

My code:

![image](https://user-images.githubusercontent.com/8006634/109357570-2bfb9180-7861-11eb-997e-c16e6acc57ca.png)

The result:

![image](https://user-images.githubusercontent.com/8006634/109357613-42a1e880-7861-11eb-9f96-d2601255ef31.png)

Thanks

**Comment by sentient-8** [comment]
In your code use the following:
`:hashtags="(serie.Title + ',InkAndTales').replace(/\s*,\s*/g, ',').replace(/\s+/g, '_')"`

This will remove all white spaces around the commas and then convert any consecutive whitespaces to a single underscore.

**Comment by yaeru** [comment]
Awesome, thanks!
