### ISSUE TITLE
Use component inside network comp.

### ISSUE THREAD

**Issue by adalberth** [nicolasbeauvais/vue-social-sharing#27]
Is it possible to use other components inside the network component?
e.g.
```js
<network network="facebook">
    <my-custom-icon></my-custom-icon>
</network>
```

**Comment by adalberth** [comment]
Found a solution.

Import your component global
```js
import Icon from '@/components/Icon'
Vue.component('my-custom-icon', Icon);
```

and use  *inline-template* `<social-sharing** url="my-fansy-url" inline-template>`

**Comment by nicolasbeauvais** [comment]
Thank for sharing your solution @adalberth

**Comment by schmod** [comment]
Are there any options that don't require this to be a global import?
