### ISSUE TITLE
vue 3 support?

### ISSUE THREAD

**Issue by yiwiz-sai** [nicolasbeauvais/vue-social-sharing#271]
could it support vue 3 ?

app.use(VueSocialSharing) ?

**Comment by brambekkers** [comment]
That would be awesome!

**Comment by PickleNik** [comment]
indeed

**Comment by picks44** [comment]
Yep 👍

**Comment by HermanLederer** [comment]
Would love to see Vue 3 support

**Comment by pinsara-aasith** [comment]
Please add vue 3 support

**Comment by reslear** [comment]
hid @nicolasbeauvais, thank you for great plugin, do you have plans for add vue3 support?)

**Comment by WillianBabuu** [comment]
Thanks for the plugin, please add vue 3 support

**Comment by anhzf** [comment]
Yes, this awesome plugin should have it

**Comment by CKGrafico** [comment]
Trying to help with #278

**Comment by nicolasbeauvais** [comment]
Hey everyone, thanks to @CKGrafico a first alpha build with Vue 3 support is available, please tell me how it works for you https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v4.0.0-alpha1

**Comment by mykhailotarabtsov** [comment]
@nicolasbeauvais Hello, thank you for Vue 3 support.
I'm trying it right now, and it will not render elements I write inside `ShareNetwork` component.
In main.js I used it in the next way:
`import VueSocialSharing from 'vue-social-sharing'`
`app.use(VueSocialSharing)`

**Comment by mykhailotarabtsov** [comment]
Hello @nicolasbeauvais .
I found why slot will not be rendered.
There is a mistake in file `share-network.js` on line **200**
Should be like this - `return h(this.tag, node, typeof this.$slots.default === 'function' ? this.$slots.default() : null)`

**Comment by nicolasbeauvais** [comment]
Thank you @mykhailotarabtsov, I made the change you suggested and pushed it to a new version, good catch.

**Comment by echooohce** [comment]
how to custom share network in vue3?
 createApp(App).use(VueSocialSharing, {
  networks: {
    fakeblock: 'https://fakeblock.com/share?url=@url&title=@title',
  }
}) is error,
error info: 'Uncaught (in promise) Error: Network xx does not exist'

**Comment by wzjiscode** [comment]
> how to custom share network in vue3?
> createApp(App).use(VueSocialSharing, {
> networks: {
> fakeblock: 'https://fakeblock.com/share?url=@url&title=@title',
> }
> }) is error,
> error info: 'Uncaught (in promise) Error: Network xx does not exist'

Has this problem been solved?

**Comment by muhghazaliakbar** [comment]
Has anyone tried this with Laravel + Vue.JS 3? How to import this lib inside component?

**Comment by romain130492** [comment]
> Hey everyone, thanks to @CKGrafico a first alpha build with Vue 3 support is available, please tell me how it works for you https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v4.0.0-alpha1

the link is dead

**Comment by CKGrafico** [comment]
> > Hey everyone, thanks to @CKGrafico a first alpha build with Vue 3 support is available, please tell me how it works for you https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v4.0.0-alpha1
> 
> the link is dead

https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v4.0.0-alpha4

**Comment by rdhelms** [comment]
@nicolasbeauvais @CKGrafico We're looking to migrate to Vue 3 and I'm about to try out that alpha build, but I'm seeing the "wontfix" label on this issue and the tagged alpha version is quite old...is this still going to get a 4.0.0 version supporting Vue 3? Or is there a new package I should be looking at?

**Comment by CKGrafico** [comment]
@rdhelms on my side I've never used it again but after a quick search looks like still the best option, let's encourage @nicolasbeauvais to update it or add more admins to the repo :)

At the end this is open source and all of us have a life behind the computer.

**Comment by rdhelms** [comment]
@CKGrafico 100% agree 👍

I'd be happy to help @nicolasbeauvais here in this repo if that's needed, or else @CKGrafico let me know if you're interested in forking it and publishing under a new name. `vue-share-network`? Or `@ckgrafico/vue-social-sharing`?

**Comment by CKGrafico** [comment]
Thanks for thinking into add me but nowadays I’m more focused into universal components like I’m doing in papanasi.js.org can be a good component to add there but is still in a early version @rdhelms  but thanks :)
