### ISSUE TITLE
messenger

### ISSUE THREAD

**Issue by HA-NA123** [nicolasbeauvais/vue-social-sharing#272]
messenger pop up not opening like the other socail network.

**Comment by HA-NA123** [comment]
i have used messenger network but it does not allow me to open the messenger and share the link or text .

**Comment by MFrizzy** [comment]
Hey, the messenger link is : `messenger: 'fb-messenger://share/?link=@u',`
It only works on mobile device.. 
Shouldn't not be used for now

**Comment by HA-NA123** [comment]
ok but i want also on desktop 

> Hey, the messenger link is : `messenger: 'fb-messenger://share/?link=@u',`
> It only works on mobile device..
> Shouldn't not be used for now

ok but i want on desktop also.
