### ISSUE TITLE
Adding it in nuxt, the style not being set.

### ISSUE THREAD

**Issue by BroJenuel** [nicolasbeauvais/vue-social-sharing#276]
Adding it in nuxt, the style not being set.

![image](https://user-images.githubusercontent.com/31676163/116531060-59bc8f80-a911-11eb-852e-2dce9498d124.png)

**Comment by khoazero123** [comment]
Same issue with me.

**Comment by nicolasbeauvais** [comment]
Hello, this is a [renderless component](https://github.com/nicolasbeauvais/vue-social-sharing#what-is-a-renderless-component) you need to do your own styling

**Comment by BroJenuel** [comment]
> Hello, this is a [renderless component](https://github.com/nicolasbeauvais/vue-social-sharing#what-is-a-renderless-component) you need to do your own styling

oh, I already did it 18 15 days ago.. but thanks 😊
