### ISSUE TITLE
No rendering using with Nuxt SSR

### ISSUE THREAD

**Issue by Olusiji** [nicolasbeauvais/vue-social-sharing#279]
It seems like this should work, but I can't seem to figure out how.

I'm using the example from the guide. The component shows up as expected in vue devtools but doesn't render any content in the HTML. 

I know this is a renderless component, but I can't seem to find a way to get the information to render on the page.

How Im Using The Component
`<div>
            <ShareNetwork 
              network="twitter" 
              url="https://news.vuejs.org/issues/180"
              title="Say hi to Vite! A brand new, extremely fast development setup for Vue."
              description="This week, I’d like to introduce you to 'Vite', which means 'Fast'. It’s a brand new development setup created by Evan You."
              quote="The hot reload is so fast it\'s near instant. - Evan You"
              hashtags="vuejs,vite,javascript"
              twitter-user="youyuxi"
            >
              <i class="fab fah fa-lg fa-twitter" />
              <span>Share on Twitter</span>
            </ShareNetwork>
          </div>`

HTML Rendered
`<div data-v-1c5a9f44=""><!----></div>`

**Comment by quicombo** [comment]
@Olusiji i think its because of vue 3.0 version in 4.0.0-alpha social-sharing module. Just make the same (switched to 3.0.7 and its working)

**Comment by Olusiji** [comment]
I think the 4.0.0-alpha should not be the default version when the package is installed as Vue 3 is not yet widely used especially in large scale projects at the moment

**Comment by nicolasbeauvais** [comment]
Hello, thank you for reporting the issue, I fixed the npm repository, v3 should be the default version now.
