### ISSUE TITLE
Ability to extends networks list

### ISSUE THREAD

**Issue by Vadiok** [nicolasbeauvais/vue-social-sharing#28]
Please add method to push custom networks to default network list.

**Comment by nicolasbeauvais** [comment]
Hello @Vadiok, this is a great idea, I will work on it when I manage to get some time :)

**Comment by nicolasbeauvais** [comment]
Hello @Vadiok,

I implemented the possibility to add/override networks in the `2.3.1` version of the library https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v2.3.1

Thank you for your input on this feature :+1:
