### ISSUE TITLE
Component not rendering

### ISSUE THREAD

**Issue by galipmedia** [nicolasbeauvais/vue-social-sharing#280]
I have successfully used this component before in another project. I am installing it and including it all correctly. Not getting any errors anywhere but where the component should render it just has 
```
<!---->
```
 I am completely lost as to why its doing this. Any ideas?

**Comment by galipmedia** [comment]
I just installed version 3.0.7 and it works fine. Perhaps version 4.0 only works for Vue 3 ?

**Comment by nekdolan** [comment]
Same here. Thanks for the tip @galipmedia .
Not sure why npm was installing 4.0 alpha by default.

**Comment by nicolasbeauvais** [comment]
Hello @galipmedia and @nekdolan, indeed v4 is an alpha release for vue 3 compatibility and will not be compatible with vue 2.
