### ISSUE TITLE
Cannot set property '$SocialSharing' of undefined

### ISSUE THREAD

**Issue by abdurahmanrizal** [nicolasbeauvais/vue-social-sharing#281]
I use this package in vue 3 for register globally with const app = createApp(App).use(VueSocialSharing) and import VueSocialSharing from 'vue-social-sharing', how can i fix that? please help me, thanks

**Comment by abdurahmanrizal** [comment]
solved() : to update package with npm install vue-social-sharing@next

**Comment by gspgsp** [comment]
> solved() : to update package with npm install vue-social-sharing@next

this will install 4.0.0-alpha4, and everything works well.
