### ISSUE TITLE
Sharing to Telegram is not working

### ISSUE THREAD

**Issue by CheaVanto** [nicolasbeauvais/vue-social-sharing#289]

**Comment by devit-chea** [comment]
Not work yet?

**Comment by aacassandra** [comment]
works for me, im using this for nuxt project

**Comment by vin-ni** [comment]
i also have problems with it. Could you send some example?

I have:
```html
        <div class="menu-item menu-item--social--telegram">
          <ShareNetwork
            aria-label="telegram"
            network="telegram"
            title="test"
            description="test"
          >
            <iconTelegram />
          </ShareNetwork>
        </div>
```

And I only recieve this:
![IMG_0028](https://user-images.githubusercontent.com/9806572/140105266-3ac096d6-b41f-46f3-9b2f-302ac68b69ba.PNG)
![IMG_0029](https://user-images.githubusercontent.com/9806572/140105281-5f7b5b71-6606-4442-8e2a-9646b52c2539.PNG)
