### ISSUE TITLE
Blocked a frame with origin <some https> from accessing a cross-origin frame

### ISSUE THREAD

**Issue by ra79sta** [nicolasbeauvais/vue-social-sharing#290]
```
> Uncaught DOMException: Blocked a frame with origin https://ter.com/ from accessing a cross-origin frame.
>     at Re (https:/ter/js/chunk-vendors.328909a9.js:102:83397)
>     at Object.get (https://ter/js/chunk-vendors.328909a9.js:102:78690)
>     at Object.get (https://ter/js/chunk-vendors.328909a9.js:102:118066)
>     at https://ter/js/chunk-vendors.328909a9.js:120:45774
> Re @ reactivity.esm-bundler.js:962
> (anonymous) @ reactivity.esm-bundler.js:438
> get @ runtime-core.esm-bundler.js:6242
> (anonymous) @ vue-social-sharing.js:1
> setInterval (async)
> share @ vue-social-sharing.js:1
> onclick @ vue-social-sharing.js:1
```

I am using Vue 3. What ever social network I share  except twitter I get this error in console. Is anyone knows the solution for this problem
@nicolasbeauvais

**Comment by ra79sta** [comment]
@nicolasbeauvais 
Is anyone has the same issue  cross-origin frame as I am? 
Thank you

**Comment by lxt-ing** [comment]
I have the same issue too. My project uses Vue + egg + ssr. 
I want to share my site , so I use the components. 
I install the it with  "vue-social-sharing": "^4.0.0-alpha4", then import and use it.
import VueSocialSharing from 'vue-social-sharing'
app.use(VueSocialSharing)

In my Page 
 ```
<ShareNetwork
                network="LinkedIn"
                url="https://vuejs.org/"
                title="xxx"
                description="sysy"
                quote="The hot reload is so fast it\'s near instant. - Evan You"
                hashtags="vuejs,vite"
              >
                Share on LinkedIn
            </ShareNetwork>
```

and got the error: 
Uncaught DOMException: Blocked a frame with origin "http://localhost:7001" from accessing a cross-origin frame.

**Comment by pakond** [comment]
I have the same issue with vue3 composition api.
![image](https://user-images.githubusercontent.com/10902317/147359716-a8f348aa-0f78-4292-9f94-a2aa5bddb02c.png)

**Comment by i-defranca** [comment]
I have the same issue with nuxt ssr

**Comment by Manu-Geotourist** [comment]
I am also having same issue in vue 3

**Comment by ZuulAndRibbon** [comment]
I have the same error.How to solve it?

**Comment by weddingdj** [comment]
Same issue here, using vue 3

**Comment by udomnohara** [comment]
Is there any solve?

**Comment by NaufalRivaldi** [comment]
Same issue here, using vue 3

**Comment by GefeiSHEN** [comment]
Same issue here, using vue 3 and nuxt 3 rc6

**Comment by focaloid-dev** [comment]
is there any solution for this ? via directive or anything ?

**Comment by DFoxinator** [comment]
has anyone figured out how to fix this?

**Comment by lxt-ing** [comment]
你的邮件我已收到，我会尽快处理
