### ISSUE TITLE
Share to Linkedin not working (desktop)

### ISSUE THREAD

**Issue by jonalxh** [nicolasbeauvais/vue-social-sharing#292]
Hi, I'm currently using your component and it works very nice, but some months ago the Linkedin option is not working, it just says: **Something went wrong. Refresh the page**, I have everything configured well as the docs say. 

I have been looking for andI found that the sharing url that you open is in the following format:
`https://www.linkedin.com/shareArticle?url={url}&title={title}&summary={text}&source={provider}`

But the 2020 way to directly open a sharing window is:
`https://www.linkedin.com/sharing/share-offsite/?url={url}`

Can you please solve the issue? Or do you want me to do a PR?

**Comment by jb-thery** [comment]
You can override default link see docs -> https://github.com/nicolasbeauvais/vue-social-sharing#extending-the-network-list

**Comment by Norbert-Nagy-SG** [comment]
This is still an issue!

**Comment by jonalxh** [comment]
I see you have merged some changes. Are they now in the npm package?

**Comment by nicolasbeauvais** [comment]
Hello @jonalxh, it has been published in version 3.0.9 https://www.npmjs.com/package/vue-social-sharing

**Comment by jonalxh** [comment]
Thanks, I'll update it to check.

**Comment by michermd** [comment]
Hello @nicolasbeauvais, I am still facing the issue on linkedin. I have also tried to overwrite it like you mentioned above but no success. I am using latest version 3.0.9
Any pointers?

**Comment by jonalxh** [comment]
Same here, LinkedIn is no longer working, even overwritting the links as you suggest.

**Comment by martygraphy** [comment]
Hello would it be possible to add : 

  _linkedin: 'https://www.linkedin.com/sharing/share-offsite/?url=@u',_

In the src/networks.js file on the version 4-alpha ? 

Thanks in advance
