### ISSUE TITLE
Server side rendering support for Vue 2.x

### ISSUE THREAD

**Issue by tushararora** [nicolasbeauvais/vue-social-sharing#3]
While using it with SSR in Vue 2.x `window is not defined` error is thrown.

**Comment by nicolasbeauvais** [comment]
I will take a look into this during the weekend as I never played with SSR before. Do not hesitate making a PR if you want a quick patch!

**Comment by nicolasbeauvais** [comment]
Couldn't get the `window is not defined` error, would you mind sharing your code ?

**Comment by tushararora** [comment]
Actually error comes from plugin itself on these lines - 

https://github.com/nicolasbeauvais/vue-social-sharing/blob/master/src/social-sharing.js#L3
https://github.com/nicolasbeauvais/vue-social-sharing/blob/master/src/social-sharing.js#L49

Need to check for existence of window object. Default value of 'url' prop can't get location href during ssr.

**Comment by ram-you** [comment]
Have the same issue.

**Comment by ram-you** [comment]
npm version still 1.1.1 and not the last 1.1.2

**Comment by nicolasbeauvais** [comment]
@ram-you good catch, v1.1.2 is now released on npm.

I'm working on the SSR compatibility and should have a working version soon

**Comment by nicolasbeauvais** [comment]
Support for SSR is now tagged (v2.0.0), the DOM has been changed a little to make it work on SSR:
```html
<social-sharing url="https://vuejs.org/" inline-template>
  <div>
      <network network="facebook">
        <i class="fa fa-facebook"></i> Facebook
      </network>
      <network network="twitter">
        <i class="fa fa-twitter"></i> Twitter
      </network>
      <network network="googleplus">
        <i class="fa fa-google-plus"></i> Google +
      </network>
      <network network="pinterest">
        <i class="fa fa-pinterest"></i> Pinterest
      </network>
      <network network="reddit">
        <i class="fa fa-reddit"></i> Reddit
      </network>
      <network network="linkedin">
        <i class="fa fa-linkedin"></i> LinkedIn
      </network>
      <network network="whatsapp">
        <i class="fa fa-whatsapp"></i> Whatsapp
      </network>
  </div>
</social-sharing>
```

readme.md has been updated accordingly.

**Comment by maziarz** [comment]
It would be pretty cool to turn this into a nuxt.js module :-)
