### ISSUE TITLE
Not working in nuxt 2.15.7

### ISSUE THREAD

**Issue by na86** [nicolasbeauvais/vue-social-sharing#301]
Hi there, i love this module and i'm using it for a long time now! 

Migrating from 3.0.4 to 3.0.8

Unfortunately both the plugin ( Vue.use(SocialSharing) ) 
and the module ('vue-social-sharing/nuxt')  are not working in nuxt. 

got this error in console 

` ERROR  Failed to compile with 1 errors This dependency was not found: * vuex in ./.nuxt/index.js`

and nuxt-error says

`Unexpected token '!'`

Any ideas? I'm i missing something? 
thank you!

**Comment by Norbert-Nagy-SG** [comment]
Its working for me with the exact same version of nuxt. I'm using as a module in `nuxt.config.js`:
```
modules: ['vue-social-sharing/nuxt']
```

Your error sad that `vuex` was not found. You don't need to specify vuex as a module in nuxt:
> The store directory contains your Vuex Store files. The Vuex Store comes with Nuxt out of the box but is disabled by default. Creating an index.js  file in this directory enables the store.

https://nuxtjs.org/docs/directory-structure/store/

**Comment by na86** [comment]
Hi @Norbert-Nagy-SG 

thank you for your help :) 

The problem is my website it's using vuex perfectly. I'm actually a vuex abuser  from the first hour! 😆 
I've solved anyway switching to an older version of the plugin. 

Closing it. Maybe one day someone will find an answer to this issue.. 
Bye
