### ISSUE TITLE
Facebook description

### ISSUE THREAD

**Issue by rassembs** [nicolasbeauvais/vue-social-sharing#308]
I tried to add a description to Facebook share post but didn't work it's abandoned or there is a solution ?

**Comment by tsangaris** [comment]
In my case, only Twitter is working as expected. Facebook and LinkedIn are not working properly.

**Comment by NperronNmedia** [comment]
Same issue here! Looks like only the Hashtage and Url properties work for Facebook.

**Comment by HashimJaved09** [comment]
I am having the same issue also as mentioned in the Documentation **quotes** also don't work.

<img width="832" alt="Screenshot 2022-06-27 at 8 37 43 PM" src="https://user-images.githubusercontent.com/27362494/175979207-6e7b6858-b34f-4001-9928-2681b088e6be.png">

**Comment by shieldcy** [comment]
I also have an issue with Facebook. Doesn't work as expected

**Comment by bfine9618** [comment]
same
