### ISSUE TITLE
Messenger isn't working

### ISSUE THREAD

**Issue by HashimJaved09** [nicolasbeauvais/vue-social-sharing#316]
I have recently used this package and I am having problems while sharing with the messenger. I am having following error in the console: 

_iframe.html:1 Failed to launch 'fb-messenger://share/?link=https%3A%2F%2Fnews.vuejs.org%2Fissues%2F180' because the scheme does not have a registered handler._

**Comment by KevinHoppeLS** [comment]
Any updates here? Same issue

**Comment by algoparticular** [comment]
No updates still  🥲

**Comment by Zw2b4ck** [comment]
same issue
