### ISSUE TITLE
 vue3 error ‘’Network fakeblock does not exist‘’

### ISSUE THREAD

**Issue by xiami2020** [nicolasbeauvais/vue-social-sharing#321]
use  vue3.2 ,  "vue-social-sharing": "^4.0.0-alpha4"

main.ts
```
app.use(VueSocialSharing,{
  networks: {
    fakeblock: 'https://baidu.com?url=@url&title=@title'
  }
})
app.use(ElementPlus).mount('#app')
```

template
```
  <ShareNetwork
    network="fakeblock"
    url="https://news.vuejs.org/issues/180"
    title="Say hi to Vite! A brand new, extremely fast development setup for Vue."
  >
    <i class="fab fah fa-lg fa-react"></i>
    <span>Custom Network</span>
  </ShareNetwork>
```

error is ‘’Network fakeblock does not exist‘’  ,

**Comment by Julyemerson** [comment]
Maybe you forgot the 's'. 

<ShareNetwork
    **networks**="fakeblock"
    url="https://news.vuejs.org/issues/180"
    title="Say hi to Vite! A brand new, extremely fast development setup for Vue."
  >
    <i class="fab fah fa-lg fa-react"></i>
    <span>Custom Network</span>
  </ShareNetwork>

**Comment by xiami2020** [comment]
> Maybe you forgot the 's'.
> 
> <ShareNetwork **networks**="fakeblock" url="https://news.vuejs.org/issues/180" title="Say hi to Vite! A brand new, extremely fast development setup for Vue."
> 
> > 
> 
> ```
> <i class="fab fah fa-lg fa-react"></i>
> <span>Custom Network</span>
> ```

thanks for the reply，Adding 's' reported another error
![image](https://user-images.githubusercontent.com/108419840/186449881-fc7bd67c-81a2-44c5-855c-53ee3b2c580c.png)
