### ISSUE TITLE
Nuxt3 nuxt.config.ts module error

### ISSUE THREAD

**Issue by bonomite** [nicolasbeauvais/vue-social-sharing#324]
stackblitz: https://stackblitz.com/edit/nuxt-starter-xjjuoe?file=nuxt.config.ts,tsconfig.json

![image](https://user-images.githubusercontent.com/13803343/193321395-d172dce4-db6f-474b-900f-ed284b805098.png)

**Comment by HochinChan** [comment]
+1

**Comment by oawebdev** [comment]
![image](https://user-images.githubusercontent.com/43724086/197563071-18e5aa6c-dec3-4832-83b4-e4eb33d28b0f.png)

**Comment by oawebdev** [comment]
![image](https://user-images.githubusercontent.com/43724086/197563362-6e0ae639-dec9-4886-9c2f-cc506b2d6e80.png)
Nuxt 3.0.0-rc.11
[https://github.com/nicolasbeauvais/vue-social-sharing/issues/315](https://github.com/nicolasbeauvais/vue-social-sharing/issues/315)

**Comment by kyng-cytro** [comment]
I ran into this issue—I fixed mine by creating a custom plugin.

To do this, create a new file in the /plugins directory. "plugins/vue-social-sharing.client.ts" it's content should loop like this:

```javascript
import VueSocialSharing from "vue-social-sharing";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VueSocialSharing);
});

```
Hope this helps.

**Comment by phailee** [comment]
![err](https://user-images.githubusercontent.com/22312202/210037985-977a3cb5-6923-400c-90f4-deb8a8e1407f.jpg)

I am getting this error after using above solution

**Comment by sanyaches** [comment]
Nuxt 3.0.0, it's still an issue

**Comment by kyng-cytro** [comment]
Here is a link to the project where I got it working.
[Link ](https://github.com/kyng-cytro/code-streaks/blob/main/plugins/vue-social-sharing.client.ts) hope this helps.

**Comment by sanyaches** [comment]
@kyng-cytro Thanks for sharing that, I noticed that it's working because of the version of vue-social-sharing package

**So, the working recipe**:
1) Install the version below, run `yarn add vue-social-sharing@next` or `npm install --save vue-social-sharing@next`:
`"vue-social-sharing": "^4.0.0-alpha4"` - Works, for Vue 3 
`"vue-social-sharing": "3.0.9"` - Does not, for Vue 2

2) Use it like a plugin in Nuxt, not a module
> I ran into this issue—I fixed mine by creating a custom plugin.
> 
> To do this, create a new file in the /plugins directory. "plugins/vue-social-sharing.client.ts" it's content should loop like this:
> 
> ```js
> import VueSocialSharing from "vue-social-sharing";
> 
> export default defineNuxtPlugin((nuxtApp) => {
>   nuxtApp.vueApp.use(VueSocialSharing);
> });
> ```
> 
> Hope this helps.

**UPD**: Of course, Nuxt 3.0.0 is meant

**Comment by kyng-cytro** [comment]
Awesome that should fix for everyone now.

**Comment by sanyaches** [comment]
@bonomite Could you recheck that, please?

**Comment by bonomite** [comment]
@sanyaches I started a new Nuxt3 project on stackblitz,, installed vue-social-sharing@next for vue3 support per instructions. Now I get a different error: 
![image](https://user-images.githubusercontent.com/13803343/212213614-50f8995a-f4e4-4967-8325-b38e64cdc5ad.png)

stackblitz: https://stackblitz.com/edit/nuxt-starter-nslbhm?file=package.json,app.vue&file=nuxt.config.ts

**Comment by bonomite** [comment]
I started a new Nuxt3 project, installing the @next version, and after making a plug-in like instructed above, I did get a error that said `"it could not resolve <ShareNetwork>"`, I just wrapped it in a `<ClientOnly>` tag, and it worked.
![image](https://user-images.githubusercontent.com/13803343/212214975-b1c813b1-a25e-4685-8746-9490ee7fbe9c.png)

is the button supposed to be styled?

stackblitz: https://stackblitz.com/edit/nuxt-starter-nslbhm?file=package.json,app.vue&file=nuxt.config.ts,plugins%2Fvue-social-sharing.client.ts
