### ISSUE TITLE
Issue Uncaught DOMException: Permission denied to access property "__v_isRef" on cross-origin object

### ISSUE THREAD

**Issue by pmadrigal95** [nicolasbeauvais/vue-social-sharing#325]
Hello.

I was using this tutorial https://nicolasbeauvais.github.io/vue-social-sharing/?path=/story/vuesocialsharing--multiple-share-networks as example on my project, but I got the following error : 
"Uncaught DOMException: Permission denied to access property "__v_isRef" on cross-origin object"

![image](https://user-images.githubusercontent.com/23517022/193377232-176f8150-933a-4756-a8ee-b351dcac492a.png)

At the ui level it seems that it is working but the console has the error previously shown

data 
`
networks: [
                {
                    network: 'email',
                    name: 'Email',
                    icon: 'mdi-email-outline',
                    color: '#333333',
                },
                {
                    network: 'facebook',
                    name: 'Facebook',
                    icon: 'mdi-facebook',
                    color: '#1877f2',
                },
                {
                    network: 'linkedin',
                    name: 'LinkedIn',
                    icon: 'mdi-linkedin',
                    color: '#007bb5',
                },
                {
                    network: 'skype',
                    name: 'Skype',
                    icon: 'mdi-skype-business',
                    color: '#00aff0',
                },
                {
                    network: 'telegram',
                    name: 'Telegram',
                    icon: 'mdi-send-circle',
                    color: '#0088cc',
                },
                {
                    network: 'tumblr',
                    name: 'Tumblr',
                    icon: 'mdi-alpha-t-box-outline',
                    color: '#35465c',
                },
                {
                    network: 'twitter',
                    name: 'Twitter',
                    icon: 'mdi-twitter',
                    color: '#1da1f2',
                },
                {
                    network: 'whatsapp',
                    name: 'Whatsapp',
                    icon: 'mdi-whatsapp',
                    color: '#25d366',
                },
                {
                    network: 'wordpress',
                    name: 'Wordpress',
                    icon: 'mdi-wordpress',
                    color: '#21759b',
                },
            ],
            `
            
            `{
                url: this.link,
                title: `Perfil de ${this.user.name}`,
                description: `BUO: Revolucioná la forma de certificar tus habilidades y experiencias`,
                quote: 'BUO: Revolucioná la forma de certificar tus habilidades y experiencias',
                hashtags: `Buo Shareable Link`,
            }`

Template

`                        <ShareNetwork
                            v-for="network in networks"
                            :network="network.network"
                            :key="network.network"
                            :url="sharing.url"
                            :title="sharing.title"
                            :description="sharing.description"
                            :quote="sharing.quote"
                            :hashtags="sharing.hashtags"
                            twitterUser="BuoSupport"
                        >
                            <v-tooltip top>
                                <template v-slot:activator="{ on, attrs }">
                                    <v-btn
                                        class="ma-2"
                                        fab
                                        x-small
                                        outlined
                                        :color="network.color"
                                        v-bind="attrs"
                                        v-on="on"
                                    >
                                        <v-icon :color="network.color">
                                            {{ network.icon }}
                                        </v-icon>
                                    </v-btn>
                                </template>
                                <span>{{ network.network }}</span>
                            </v-tooltip>
                        </ShareNetwork>
                       `
                       
Version
"vue": "^2.6.11",
"vue-social-sharing": "^3.0.9",

Browser

Firefox 105

Could you please help me and tell me how I could solve the problem?

**Comment by ankurk91** [comment]
Same issue on Windows 10, Firefox

**Comment by ankurk91** [comment]
keep this alive

**Comment by ilic993** [comment]
Happens only in Firefox and with Facebook network

**Comment by ephraim-ikido** [comment]
Happens to me also in google authentication on firefox

**Comment by skb-hashchi** [comment]
Also with me on Google Chrome and Web3auth authentication

**Comment by wilmanbhigu** [comment]
> Hello.
> 
> I was using this tutorial https://nicolasbeauvais.github.io/vue-social-sharing/?path=/story/vuesocialsharing--multiple-share-networks as example on my project, but I got the following error : "Uncaught DOMException: Permission denied to access property "__v_isRef" on cross-origin object"
> 
> ![image](https://user-images.githubusercontent.com/23517022/193377232-176f8150-933a-4756-a8ee-b351dcac492a.png)
> 
> At the ui level it seems that it is working but the console has the error previously shown
> 
> data `networks: [ { network: 'email', name: 'Email', icon: 'mdi-email-outline', color: '#333333', }, { network: 'facebook', name: 'Facebook', icon: 'mdi-facebook', color: '#1877f2', }, { network: 'linkedin', name: 'LinkedIn', icon: 'mdi-linkedin', color: '#007bb5', }, { network: 'skype', name: 'Skype', icon: 'mdi-skype-business', color: '#00aff0', }, { network: 'telegram', name: 'Telegram', icon: 'mdi-send-circle', color: '#0088cc', }, { network: 'tumblr', name: 'Tumblr', icon: 'mdi-alpha-t-box-outline', color: '#35465c', }, { network: 'twitter', name: 'Twitter', icon: 'mdi-twitter', color: '#1da1f2', }, { network: 'whatsapp', name: 'Whatsapp', icon: 'mdi-whatsapp', color: '#25d366', }, { network: 'wordpress', name: 'Wordpress', icon: 'mdi-wordpress', color: '#21759b', }, ],`
> 
> ```
>         `{
>             url: this.link,
>             title: `Perfil de ${this.user.name}`,
>             description: `BUO: Revolucioná la forma de certificar tus habilidades y experiencias`,
>             quote: 'BUO: Revolucioná la forma de certificar tus habilidades y experiencias',
>             hashtags: `Buo Shareable Link`,
>         }`
> ```
> 
> Template
> 
> ` <ShareNetwork v-for="network in networks" :network="network.network" :key="network.network" :url="sharing.url" :title="sharing.title" :description="sharing.description" :quote="sharing.quote" :hashtags="sharing.hashtags" twitterUser="BuoSupport" > <v-tooltip top> <template v-slot:activator="{ on, attrs }"> <v-btn class="ma-2" fab x-small outlined :color="network.color" v-bind="attrs" v-on="on" > <v-icon :color="network.color"> {{ network.icon }} </v-icon> </v-btn> </template> <span>{{ network.network }}</span> </v-tooltip> </ShareNetwork>`
> 
> Version "vue": "^2.6.11", "vue-social-sharing": "^3.0.9",
> 
> Browser
> 
> Firefox 105
> 
> Could you please help me and tell me how I could solve the problem?

does this happen in development? I think it's caused by the URL you use. When the URL used does not use SSL (https://) then this error will occur
