### ISSUE TITLE
dynamic list of networks

### ISSUE THREAD

**Issue by cswebdev** [nicolasbeauvais/vue-social-sharing#33]
Hello,

its not possible for me to loop the network list dynamically. how is it possible to read out the list of networks from p. e. vuex, and then render the list through v-for?

thanks for help

**Comment by edwinnnss** [comment]
I think you can try to loop with v-for and set network prop to set by your loop item
```
<template v-for="item in items")>
  <network :network="item.type">
    {{ item.title }}
  </network>
</template>
```

**Comment by nicolasbeauvais** [comment]
Hello @cswebdev, this should work fine:

```javascript
var SocialSharing = require('vue-social-sharing');

VueSocialSharing.data().networks // => {} containing all networks
```
