### ISSUE TITLE
How to update after data in component loads?

### ISSUE THREAD

**Issue by patrickbolle** [nicolasbeauvais/vue-social-sharing#34]
Hi love the plugin so far.

I want to update the twitter title, etc after the data from my vue-resource call loads. 

In another plugin (vue-head) I can emit an .updateHead() method that will update the plugin to essentially resync the data.

Is there anything I can do here?

Thanks so much!

**Comment by nicolasbeauvais** [comment]
Hello @patrickbolle,

you can do that by using vuejs binding and computed properties:

```javascript
Vue.component('my-component', {
  computed: {
    url() {
      return 'some dynamic url';
    },

    title() {
      return 'some dynamic title';
    },

    description() {
      return 'some dynamic description';
    },
  }
})
```
```html
<my-component>
  <social-sharing :url="url" :title="title" :description="desciption" v-cloak inline-template>
    ...
  </social-sharing>
</my-component>
```
