### ISSUE TITLE
Can I dynamically change buttons names in the template?

### ISSUE THREAD

**Issue by CodeLookBook** [nicolasbeauvais/vue-social-sharing#35]
Hello. First off all, Thank you for your 'vue-social-sharing'.

Question:
I have multi-language app. Pleas tell, is there any possibility to change buttons names dynamically?

**Comment by nicolasbeauvais** [comment]
Hello @CodeLookBook,

What do you mean exactly by "buttons names"?

**Comment by CodeLookBook** [comment]
Hello! ) @nicolasbeauvais 

Here is an code example from you repository. I need to have opportunity to change string - 'Share on Facebook', that is placed into `<network>` ,  dynamically.  I can't do that right now, because this value, is placed into  `inline-template`. And as I understood from VueJs docs, I cant place properties from the parent component into `inline-template`. So, I wanted to ask is there an easy way to do that? Or maybe I don't know some basics of `inline-template` usage and I have to read docs one more.

```
 <social-sharing url="https://vuejs.org/"
                      title="The Progressive JavaScript Framework"
                      description="Intuitive, Fast and Composable MVVM for building interactive interfaces."
                      quote="Vue is a progressive framework for building user interfaces."
                      hashtags="vuejs,javascript,framework"
                      twitter-user="vuejs"
                      v-cloak inline-template>
        <div>
          <ul>
            <li>
              <network network="facebook" id="facebook">
                <i class="fa fa-fw fa-facebook"></i> Share on Facebook // This string, needs to be change dynamically.
              </network>
            </li>
          </ul>
       </div>
 </social-sharing>
```

**Comment by nicolasbeauvais** [comment]
Have you tried it ?

This should work fine :)

```html
<social-sharing url="https://vuejs.org/" v-cloak inline-template>
  <div>
    <network network="facebook" id="facebook">
      <i class="fa fa-fw fa-facebook"></i> {{ trans.facebook_share }}
    </network>
  </div>
 </social-sharing>
```

```javascript
// parent-component
export default {
  data() {
    return {
      trans: {
        facebook_share: 'Share on Facebook'
      }
    }
  }
};
```

**Comment by CodeLookBook** [comment]
@nicolasbeauvais 

yeess) I have tried that.
The result of this code will be error.  This part: {{ trans.facebook_share }} will be undefined.

**Comment by nicolasbeauvais** [comment]
Here is a fiddle with a working version: https://jsfiddle.net/s7n8ap8q/

Are you using vue 2 or 1?

**Comment by CodeLookBook** [comment]
Thank you for your help!

**Comment by vishalsingh0919** [comment]
hi
how could i pass dynamic url in   <social-sharing url="https://vuejs.org/" v-cloak inline-template>

**Comment by ringoma** [comment]
I find 

> Here is a fiddle with a working version: https://jsfiddle.net/s7n8ap8q/
> 
> Are you using vue 2 or 1?

Just found that the latest version 2.4.6 cannot shows the props/data inside the component.
Is there any other measure to call the props/data from parent node?

Here is a fiddle replaced the resource with latest version: https://jsfiddle.net/gL9h63vr/1/

Thanks.

**Comment by waseema93** [comment]
hello @nicolasbeauvais
I am using vue 2 , still not getting props/data inside component with the same fiddle code i.e with  inline-template
