### ISSUE TITLE
Share with URL, title, and description not shown title and description.

### ISSUE THREAD

**Issue by mazipan** [nicolasbeauvais/vue-social-sharing#36]
Expectation : URL was shown and there is content with title and description too

**Comment by nicolasbeauvais** [comment]
Hello @mazipan,

could you provide a failing jsfiddle?

Thank you!

**Comment by mazipan** [comment]
I have project that you can see the demo here : https://mazipan.github.io/chucknorris/
And here the implementation of your `vue-social-sharing`
https://github.com/mazipan/chucknorris/blob/master/src/components/SocialSharingSection.vue

The Goal is I need to share the title and desc that I provide, buat unfortunately I just see url in the sharing window without any title and description typed in textbox sharing.

Can you help me ? Is it my fault or config that seems wrong ? Or it's knowing issue ?

**Comment by nicolasbeauvais** [comment]
Hello again @mazipan,

You misspelled "quote" here: https://github.com/mazipan/chucknorris/blob/e056b824ddb1bcf3cfce8f511d19b2db6846bd8b/src/pages/Home.vue#L13

If you want to personalize how Facebook show your link the only way is to use `og` meta tags https://developers.facebook.com/docs/sharing/webmasters

If this doesn't solve your issue feel free to re-open it :)
