### ISSUE TITLE
 stopped working dynamic facebook title and description

### ISSUE THREAD

**Issue by hardsoncore** [nicolasbeauvais/vue-social-sharing#37]
Tell me, only I have stopped working dynamic facebook title and description? Or is this a problem with updates for facebook Open Graph API?

P.S. Checked the changes in your project

**Comment by ImadSalimi** [comment]
I just had this issue too and it started just some days ago, it's not just you or the package I think it's due to some change in the way Facebook's sharer works... Hopefully the author will fix it soon ^^

**Comment by nicolasbeauvais** [comment]
Hello @hardsoncore & @ImadSalimi,

It looks like Facebook updated their sharer api. Note that there is no official documentation for the sharer.php endpoint that this library (and others) use, so it's hard to know what changed exaclty.

Facebook now ignore the title and description provided and only use the one they found with their graph API. So if you set your OG meta it should be fine (see: https://developers.facebook.com/docs/sharing/best-practices).

If you got any new info on the facebook update do not hesitate to reopen this issue. If it stay this way I will remove the title & description from the facebook endpoint in the next version of `vue-social-sharin`.
