### ISSUE TITLE
Socialize's counter

### ISSUE THREAD

**Issue by EugeneHerasymchuk** [nicolasbeauvais/vue-social-sharing#38]
Nicolas, you did an amazing job. Thank you.
Of course, the beautiful example should be socialize.js. Can you add styles similar to them? Because for this moment people use more socialize.js only because of styles and counters.

**Comment by nicolasbeauvais** [comment]
Hello @EugeneHerasymchuk,

I will not add any styling to `vue-social-sharing`, Vuejs and this library make it easy enough for you to create any style you want for the social share button. But I could certainly add some CSS to the demo and the readme.md file.

Counters are a great feature but are a little tricky to implement. Feel free to draft a PR for it if you want.

**Comment by EugeneHerasymchuk** [comment]
Ok, thanks
