### ISSUE TITLE
How do I get callbacks for success and failure sharing on 'Facebook Sharing'?

### ISSUE THREAD

**Issue by hyeokluv** [nicolasbeauvais/vue-social-sharing#39]
```
         function(response) {
              if (response && !response.error_message) {
                // response.post_id
                alert('share it!')
              } else {
                alert('cancel.')
              }
          }
```
The Facebook API introduces the above.

What's in this library?

**Comment by nicolasbeauvais** [comment]
There is no way to check for a success/failure with `vue-social-sharing` as the library share content using popups and not any API.

You can still use a variety of event triggered by the library: https://github.com/nicolasbeauvais/vue-social-sharing#available-event
