### ISSUE TITLE
please add ok (ok.ru) support

### ISSUE THREAD

**Issue by pwnz22** [nicolasbeauvais/vue-social-sharing#40]
`https://connect.ok.ru/dk?st.cmd=WidgetSharePreview&st.shareUrl={url}&st.comments={comments}`

**Comment by nicolasbeauvais** [comment]
Hello @pwnz22,

thanks for the ready to use sharing link.

You can now use ok.ru as of version `2.2.4` of this package:
```
<network network="odnoklassniki">
  <i class="fa fa-odnoklassniki"></i> Odnoklassniki
</network>
```
