### ISSUE TITLE
Email mailto: link

### ISSUE THREAD

**Issue by samburgers** [nicolasbeauvais/vue-social-sharing#42]
Any chance of also adding a regular old, but well formed email link?

Many thanks!

**Comment by Fermain** [comment]
I second this feature request, it would be very useful to have access to a mailto option

**Comment by nicolasbeauvais** [comment]
Hello @samburgers and @Fermain,

I just pushed a `v2.2.5` version with an email sharer:

```html
<network network="email">
    <i class="fa fa-envelope"></i> Email
</network>
```

Tell me if that works for you :)

**Comment by tmorehouse** [comment]
The email body should contain the URL.  Sharing just the description is kind of useless.

The URL should come before the description,separated by a percent encoded CRLF.
