### ISSUE TITLE
mailto option should include URL in message body

### ISSUE THREAD

**Issue by tmorehouse** [nicolasbeauvais/vue-social-sharing#45]
Sharing just the title and description is kind of useless. The URL needs to be in the email body, just before the description.

The URL would need to be percent encoded, followed by a percent encoded `CRLF`, then followed by the description

**Comment by ram-you** [comment]
Same thing for SMS.

**Comment by nicolasbeauvais** [comment]
Merged in #46, thanks to @tmorehouse :smile:
