### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by fsanano** [nicolasbeauvais/vue-social-sharing#47]
Hi @nicolasbeauvais, today I try install vue-social-sharing to my project on vue-webpack template.
But get this:
`[Vue warn]: Failed to mount component: template or render function not defined.`
And this is not related to [Runtime-Compiler-vs-Runtime-only ](https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only)

**Comment by nicolasbeauvais** [comment]
Hello @fsanano,

Could you provide more details on how you're trying to use `vue-social-sharing` ?

**Comment by nicolasbeauvais** [comment]
Closing for now. You can re-open the issue with more details if you still have the error

**Comment by vinicius0026** [comment]
I'm facing the same issue.

The application I'm working with is SSR.

I'm loading the module as below

```javascript
import SocialSharing from 'vue-social-sharing'

Vue.use(SocialSharing)
```

I don't think it is a bundler problem because the module is loaded both on client and server entry points. I can log the module's contents both on the server and on the browser.

The error below is shown on the browser when I navigate to the page using vue-social-share:

```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <SocialSharing>
         ...
         <App> at app/App.vue
           <Root>
```

The markup on the page is basically the same as shown in this repo README:

```vue
<social-sharing
  :url="currentUrl"
  :title="title"
  :description="description"
>
  <div>
    <network
      network="twitter"
      class="share-link"
    >
      <div class="twitter-icon"/>
    </network>
    <network
      network="facebook"
      class="share-link"
    >
      <div class="facebook-icon"/>
    </network>
  </div>
</social-sharing>
```


Relevant packages versions:
```
vue@2.5.9
vue-social-sharing@2.3.3
```

Thank you for your time!

**Comment by Saymon-biz** [comment]
Same issue

**Comment by andrijavulicevic** [comment]
I have same error today, but then I saw I missed to add inline-template to social-sharing tag. That solved same error for me.

**Comment by drrainlab** [comment]
Same issue on SSR

**Comment by flymithra** [comment]
Just add `inline-template` to component

```js
 <social-sharing
        url="https://vuejs.org/"
        inline-template
>
        <div>
            <network
                network="facebook"
            />
            <network
               network="twitter"
            />
       </div>
</social-sharing>
```
