### ISSUE TITLE
network component only allows static class list

### ISSUE THREAD

**Issue by tmorehouse** [nicolasbeauvais/vue-social-sharing#51]
the Network component only allows static class lists (i.e. a static string).  If providing a class list via a computed property (`v-bind:class=".."`), no classes get applied:

Works:
```html
<network class="foo bar" network="twitter">...</network>
```

Does not work:
```html
<network :class="['foo', 'bar']" network="twitter">...</network>
```

This PR fixes the function `<network>` component by dealing with both `staticClass` and `class` properties

**Comment by tmorehouse** [comment]
You may want to consider using this library to handle merging of the context.data in functional components:

https://github.com/alexsasharegan/vue-functional-data-merge

We use this extensively in our functional components

**Comment by nicolasbeauvais** [comment]
Thank you for the PR, the change has been tagged in https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v2.2.9

The `vue-functional-data-merge` library could indeed be a nice addition to `vue-social-sharing`

**Comment by tmorehouse** [comment]
Yeah `vue-functional-data-merge` works quite well when merging context.data with additional attributes, etc.

We use it a lot in our functional components for [Bootstrap-Vue](https://github.com/bootstrap-vue/bootstrap-vue) (it was written by one of our members)

**Comment by tmorehouse** [comment]
Hmmm, I just upgraded to 2.2.9 and v-bound classes are still not working. only classes specified as a static string.

**Comment by tmorehouse** [comment]
These lines: https://github.com/nicolasbeauvais/vue-social-sharing/blob/master/src/social-sharing-network.js#L16-L18

Do not appear in the dist files:
https://github.com/nicolasbeauvais/vue-social-sharing/blob/master/dist/vue-social-sharing.js#L58-L61

**Comment by nicolasbeauvais** [comment]
Nice catch :+1: it should be fixed in 2.2.10

**Comment by tmorehouse** [comment]
I noticed one other "caveat" when using inline-templates.  The "scope" of anything in the inline-template is that of the parent (the component with the `inline-template` prop).  If one needs to reference a computed property from their own component (in my case calculating a set of classes), one needs to reference `$parent`:
```html
<template>
 <div>
  <social-sharing ... inline-template>
    <network network="facebook" :class="$parent.myClasses">Facebook</network>
    <network network="twitter" :class="$parent.myClasses">Twitter</network>
  </social-sharing>
 </div>
</template>
<script>
export default {
  computed: {
    myClasses() {
      return ['btn', 'btn-primary']
    }
  }
}
</script>
```

Might be worth noting in the documentation.

**Comment by tmorehouse** [comment]
BTW... all is working great now...  except one can't pass a `title` prop (or other arbitrary attributes).

`Object.assign((), context.data.attrs, {.. custom data attrs here })` would work well for merging attributes, except for IE, which needs a polyfill :(
