### ISSUE TITLE
Impossible to change &noParse param to false

### ISSUE THREAD

**Issue by alexanderbelko** [nicolasbeauvais/vue-social-sharing#53]
Can't to set &noParse param in VK share url to false value.

**Comment by nicolasbeauvais** [comment]
Hello @alexanderbelko ,

I consider the noParse param to be a good default as it mimics the behavior of the other compatible networks (Facebook, Twitter...).

I implemented the possibility to override networks link in the `2.3.1` version of the library https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v2.3.1. So you are now able to remove the `noParse` param if wanted :)

You can get some documentation on the Readme file: https://github.com/nicolasbeauvais/vue-social-sharing#extending-the-network-list
