### ISSUE TITLE
Error when network isn't in the list

### ISSUE THREAD

**Issue by jbrialon** [nicolasbeauvais/vue-social-sharing#58]
Hello,

I encounter an error when the social network does't exist:
`TypeError: Cannot read property 'type' of undefined
`
is it possible that it silently fail instead of trowing an error?

thanks in advance

**Comment by nicolasbeauvais** [comment]
Hello @jbrialon,

thank you for your input, this is now fixed and throw a console warning instead :)

**Comment by jbrialon** [comment]
thanks @nicolasbeauvais 👍
