### ISSUE TITLE
Update SocialSharing when route changed

### ISSUE THREAD

**Issue by maximeparisse** [nicolasbeauvais/vue-social-sharing#59]
Hello,

I would like to use SocialSharing on different components, but the url used is the one of the first view rendered.

Example : If i land to the homepage, then i navigate to a single project, the share url will be the homepage one and not the single project one.

Is it a way to update/refresh/unmount-mount SocialSharing in this situation ?

Thanks a lot.

**Comment by nicolasbeauvais** [comment]
You can just use [dynamic props](https://vuejs.org/v2/guide/components.html#Dynamic-Props) for that:

```html
<social-sharing :url="myCurrentURL" inline-template>
  ...
</social-sharing>

<script>
      Vue.use(SocialSharing);
      new Vue({
        el: '#app',
        data: {}
        computed: {
          myCurrentURL() {
            // Dynamically return the current URL to share
          }
        }
      });
</script>
```
