### ISSUE TITLE
Dynamic props not working with webpack and single page components?

### ISSUE THREAD

**Issue by smagnaschi** [nicolasbeauvais/vue-social-sharing#60]
I have a SPA and in the socialshare component of my app I'm using vue-social-sharing plugin.
I have set inline-template and the props that I specify in the social-sharing tag are ok.
Inside the component I'm not able to reference any property of the vue component itself (for example my icons width and height that are stored as a data property and isMobileRequest that is a computed property).
Do you know if are there issues with this kind of setup or should it work as expected?

**Comment by nicolasbeauvais** [comment]
Hello @smagnaschi,

could you share some code, ideally something like a [jsfiddle](https://jsfiddle.net/) that expose the bug.

Thank you

**Comment by smagnaschi** [comment]
The fact is that in jsfiddle it works as expected.

https://jsfiddle.net/rho29t36/1/

It doesn't work in my current setup that involves webpack and single page components. I don't know how to reproduce it online so that you can look into it.

Do you confirm that it should work even with single page components and vueify?

**Comment by nicolasbeauvais** [comment]
I use `vue-social-sharing` in production in a single page component but with `vue-loader` (vueify equivalent for webpack)

It is probably due to something else in your code, maybe try with an inline component other than `vue-social-sharing` to check if it is due to the component or something else
