### ISSUE TITLE
Is it possible to know if the user has complete/cancelled the facebook share action ?

### ISSUE THREAD

**Issue by kahaus** [nicolasbeauvais/vue-social-sharing#62]
Hello,

All is in the title, is there a way to actually know if the user has completed/cancelled the facebook share action ?

Thanks

**Comment by nicolasbeauvais** [comment]
Hello @kahaus,

this issue has already been answered here: https://github.com/nicolasbeauvais/vue-social-sharing/issues/39

Short answer: We would need to make API call to Facebook (or any other provider) in order to make the share action, which is outside the scope of this package.
