### ISSUE TITLE
Unknown custom element

### ISSUE THREAD

**Issue by christophwolff** [nicolasbeauvais/vue-social-sharing#63]
Hi there,

I would like to add social network custom element icons in the Network tap i.e.

```html
<network network="facebook">
  <facebook-icon size="30"></facebook-icon>
</network>
```

I import the cusotm element correctly. When i use it outside of network it works. Any help?

**Comment by nicolasbeauvais** [comment]
Hello @christophwolff,

Have you registered your components [locally](https://vuejs.org/v2/guide/components.html#Local-Registration)?

If so you can use [global registration](https://vuejs.org/v2/guide/components.html#Global-Registration)
to make them available inside the `network` tag.
