### ISSUE TITLE
Can we get an interface to change the sharer url prefix for each social network?

### ISSUE THREAD

**Issue by xiaoyaohust** [nicolasbeauvais/vue-social-sharing#64]
For example, the prefix for pinterest is hardcoded as

https://pinterest.com/pin/create/button/?url=@url&media=@media&description=@title

However, this url will complain that there is no image for the pin if I don't pass a media value.

There is another URL which is https://www.pinterest.com/pin/find/?url=@url
It can load all the images in the page and let customer to choose one image and then create the pin. 
This fits our use case and it exactly what we want. 

But if I use this module, I find there is no way that I can change the hardcoded url to the "find" url above.

**Comment by nicolasbeauvais** [comment]
Hello @xiaoyaohust,

I implemented the possibility to override networks link in the `2.3.1` version of the library https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v2.3.1. So you can now customize the Pinterest sharing URL for your project.

You can get some documentation on the Readme file: https://github.com/nicolasbeauvais/vue-social-sharing#extending-the-network-list
