### ISSUE TITLE
Please add Viber

### ISSUE THREAD

**Issue by andrii-trush** [nicolasbeauvais/vue-social-sharing#65]
Thank you.

**Comment by nicolasbeauvais** [comment]
Hello @andrii-trush,

Would you mind sending me a link to a documentation on the Viber sharing link?

**Comment by andrii-trush** [comment]
Hello @nicolasbeauvais 
Here are official docs. https://developers viber.com/docs/tools/share-button/

**Comment by nicolasbeauvais** [comment]
@andrii-trush Viber is added in `v2.3.2` :)

https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v2.3.2

**Comment by andrii-trush** [comment]
@nicolasbeauvais  Via NPM still version 2.3.1
