### ISSUE TITLE
Add Image to social sharing

### ISSUE THREAD

**Issue by Shadomax** [nicolasbeauvais/vue-social-sharing#66]
hello i would like to know how to add an image in the social sharing since it's not described on the documentation

**Comment by nicolasbeauvais** [comment]
Hello @Shadomax,

`vue-social-sharing` is pretty basic. You can think of all `networks` tag as a `<a href="...">` HTML tag which opens a social network sharing popup.

That said you are free to use any HTML/CSS in a `network` tag like:
```
<network network="email">
    <img scr="myimg.png" />
    <!-- or anything else -->
</network>
```

The readme file only shows an example with some font awesome icons, adding some variation of styling is a good idea.

Hope this will help you integrate the library into your project :smile:
