### ISSUE TITLE
Email sharing not working

### ISSUE THREAD

**Issue by abdulrehmanguru** [nicolasbeauvais/vue-social-sharing#68]
I am using v 2.2.5. Facebook twitter, LinkedIn share are working but when i click email it just opens a new blank window
 <div class="socialicons">
                            <network network="facebook">
                                <i class="fa fa-2x fa-facebook cursor"></i>
                            </network>
                            <network network="twitter">
                                <i class="fa fa-2x fa-twitter cursor"></i>
                            </network>
                            <network network="linkedin">
                                <i class="fa fa-2x fa-linkedin cursor"></i>
                            </network>
                            <network network="email">
                                <i class="fa fa-2x fa-envelope cursor"></i>
                            </network>
                        </div>

**Comment by nicolasbeauvais** [comment]
Hello @abdulrehmanguru,

do you have an email client setup on your computer? if not your browser will open a blank window.

Please try the "Send Mail" link on this demo to check if this is coming from your lack of email client or from `vue-social-sharing`:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_mailto
