### ISSUE TITLE
Possibility to add a custom image url to the share

### ISSUE THREAD

**Issue by ImreC** [nicolasbeauvais/vue-social-sharing#69]
Hi,

Cool library! Is it also possible to add an image url to the share? I can't find the option anywhere and the images that are selected automatically for my website make no sense at all. 

Thanks!

**Comment by ImreC** [comment]
Ok just found out that this is solved through using open graph tags in your index.html body like this. 

  <meta property="og:title" content="My Shared Article Title" />
  <meta property="og:description" content="Description of shared article" />
  <meta property="og:url" content="http://example.com/my_article.html" />
  <meta property="og:image" content="http://example.com/foo.jpg" />

**Comment by olive64** [comment]
Hello ImreC,

How do you it ? i have my metas tag in my header, but don't work

```
<meta property="og:title" content="Bestfootball">
<meta property="og:description" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.">
<meta property="og:type" content="video">
<meta property="og:video" content="https://beta.bestfootball.fr/static/video/challenge/olive.mov">
<meta property="og:url" content="https://beta.bestfootball.fr//video/detail/3">
```

The code in my component : 
```
<social-sharing hashtags="bestfootball, football, soccer, challenge" twitter-user="romeyer64" inline-template>
               <div class="text-center">
                   <network network="facebook">
                     <i class="fa fa-facebook fa-5x"></i>
                   </network>
                   <network network="googleplus">
                     <i class="fa fa-google-plus fa-5x"></i>
                   </network>
                   <network network="pinterest">
                     <i class="fa fa-pinterest fa-5x"></i>
                   </network>
                   <network network="twitter">
                     <i class="fa fa-twitter fa-5x"></i>
                   </network>
               </div>
</social-sharing>
```

If you can help me :)

**Comment by ImreC** [comment]
Hi olive64,
This is not a thing that is fixed on your client side but rather on the side of the indexing that is done by the social networks. Basically, the meta tags tell social algorithms that scrape your site where to get the information like pictures descriptions etc. What this means is that the changes are not immediately reflected but will be when your site is re-indexed by facebook or google. I suggest that you leave it like this and test again after a couple of days. I just tested it and it works on my end, so you should be ok. Cheers!

**Comment by allaghi** [comment]
Hi @ImreC I am facing same issue and I did all steps that you mentioned , and it didn't work . is there anything else ?
