### ISSUE TITLE
social_shares_click

### ISSUE THREAD

**Issue by ram-you** [nicolasbeauvais/vue-social-sharing#7]
Can you explain please what is this line for ` this.$emit('social_shares_click', network, this.url);`
If I understood the purpose, it must be rather:
 ` this.$root.$emit('social_shares_click', network, this.url);`  
to be able to use it as:
` this.$root.$on('social_shares_click', callback)`

**Comment by nicolasbeauvais** [comment]
It should indeed be emitted on `$root`.

Would you like to create a PR for this?
