### ISSUE TITLE
share to fb through share dialog api

### ISSUE THREAD

**Issue by newbie78** [nicolasbeauvais/vue-social-sharing#71]
many thanks for brilliant vue component!

offer to make an additional option for sharing the link: https://www.facebook.com/dialog/share?app_id=@app_id&display=popup&href=@url&redirect_uri=@url

tnx

**Comment by nicolasbeauvais** [comment]
Hello @newbie78,

I might look into adding this option in the future, if you need it now you can override the facebook sharing link like described in the readme file: https://github.com/nicolasbeauvais/vue-social-sharing#extending-the-network-list
