### ISSUE TITLE
Do I still need to add meta tags on html?

### ISSUE THREAD

**Issue by jericopulvera** [nicolasbeauvais/vue-social-sharing#72]
Do I still need to add meta tags on html when using this package?

**Comment by nicolasbeauvais** [comment]
It depends, if the link you share is your website then you need to add the meta tags in order for Facebook/Twitter/LinkedIn graph API to work. If you share an external link it is not necessary.

`vue-social-sharing` itself does not write any meta tags.

**Comment by peoray** [comment]
Sorry if this is a dumb question, how do I add the meta tags?

**Comment by nicolasbeauvais** [comment]
Hello @peoray,

you can learn more about social sharing meta tags here https://css-tricks.com/essential-meta-tags-social-media/

**Comment by peoray** [comment]
Thanks for replying. I do know about meta tags. My question has to do how to add it with this package or workaround to it?

**Comment by nicolasbeauvais** [comment]
This package has nothing to do with meta tags, you need to set them up by yourself. Then when you share a URL using vue-social-sharing, Facebook / Linkedin and other networks will read your meta tags.
