### ISSUE TITLE
Share count

### ISSUE THREAD

**Issue by stuta** [nicolasbeauvais/vue-social-sharing#74]
It there option for share count like in https://github.com/koddr/vue-goodshare, has_counter?

**Comment by nicolasbeauvais** [comment]
Hello @stuta,

There is no such option yet for `vue-social-sharing` it may be added later but is not implemented yet.

**Comment by gimyboya** [comment]
Thank you for this wonderful component.

@nicolasbeauvais i suggest tagging this issue with enhancement label and keeping it open until the feature is implemented. 

I was about to open an issue to request for this exact feature.

**Comment by gimyboya** [comment]
The feature @stuta was referring to, has been implemented in this function for facebook https://github.com/koddr/vue-goodshare/blob/master/src/providers/Facebook.vue#L102

**Comment by nicolasbeauvais** [comment]
Hello @gimyboya, I will not keep this issue open as after further review I decided not to implement a share count. Adding this feature means loading external scripts from Facebook and other company that do not respect user privacy, and I do not want an open source library with my name on it to do that.

Vue-goodshare is a well maintained alternative and I think it's beneficial for the ecosystem to have two libraries with different vision, Vue-goodshare for a full-featured solution and Vue-social-sharing a lightweight and renderless alternative.

**Comment by gimyboya** [comment]
@nicolasbeauvais I should apologies as I didn't realize that the feature would load external scripts from facebook which we all know is invading our everyday lives. I should say that it's not everyday that we get to meet people like you in the development community. people who advocates for privacy rights.

I stand 100% by your decision and I apologies again.
