### ISSUE TITLE
Image Sharing

### ISSUE THREAD

**Issue by favoriabs** [nicolasbeauvais/vue-social-sharing#76]
Hi...won't it be great to integrate image sharing along with the text?? 
Something like:
```
 <social-sharing url="https://vuejs.org/"
                      title="The Progressive JavaScript Framework"
                      description="Intuitive, Fast and Composable MVVM for building interactive interfaces."
                      quote="Vue is a progressive framework for building user interfaces."
                      hashtags="vuejs,javascript,framework"
                      twitter-user="vuejs"
                      image="img.png"
                      inline-template>
```

**Comment by nicolasbeauvais** [comment]
Hello @favoriabs,

this won't work as most of the networks do not accept an image parameter. To share a link with an image you should use meta tags like explained in this issue: https://github.com/nicolasbeauvais/vue-social-sharing/issues/69

**Comment by favoriabs** [comment]
Thanks...the meta tags worked fine tho'.

**Comment by Shwetakonde31** [comment]
meta tags are properly generated but the image is not sharable in social media...why so?

**Comment by FRANKACQUAH** [comment]
I'm using vue-social for my social media sharing. I worked for the title and description but not the image. Any help?
