### ISSUE TITLE
Pinterest pulls in 'title' instead of 'description' prop

### ISSUE THREAD

**Issue by drpebcak** [nicolasbeauvais/vue-social-sharing#77]
I've got my pinterest buttons configured like this:

```
<social-sharing
      inline-template
      :url="url"
      :title="socialTitle"
      :media="socialImage"
      :description="socialDescription"
      :quote="socialDescription"
    >
      <span>
        <network network="pinterest">
          <div
            :class="$parent.isHover ?
              'social-wrapper-hover':
            'social-wrapper pinterest'"
          >
            <i class="icon-icomoon-pinterest"/>
            <span>Pin</span>
          </div>
        </network>
      </span>
    </social-sharing>
```

When I click the pinterest share button, it always pulls the 'title' field in as the description when previewing the pin.

I'm using version 2.3.3

**Comment by nicolasbeauvais** [comment]
Hello @drpebcak,

this is because Pinterest, unlike other networks, only has one text field (the pin description) and not a title + a description.

Did you expect to have the `title` property ignored and the pin description filled with the `vue-social-sharing` description?

**Comment by nicolasbeauvais** [comment]
Closing for now, If somebody wants to share its point of view on this you are all welcome :)
