### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by akinjide** [nicolasbeauvais/vue-social-sharing#78]
Safari version: 11.0.2 (13604.4.7.1.3)

I'm using the latest version of `vue-social-sharing`, and sharing on networks like `Facebook` and `Telegram` isn't working but `Twitter` works well. 

However, `Telegram` and `Twitter` but not `Facebook` works well on Chrome. Anyone else having this issue?

Below is the link for each network, that I'm getting
- Telegram: `tg://msg_url?url=https://www.example.com?ref=something`
- Facebook: `https://www.facebook.com/sharer/sharer.php?u=https://www.example.com?ref=something&title=&description=&quote=`

**Comment by nicolasbeauvais** [comment]
Hello @akinjide,

I sadly can't test on safari, could you check if the demo is working correctly for those failing networks?https://nicolasbeauvais.github.io/vue-social-sharing/ 

Facebook works well more me on Chrome (64).

**Comment by akinjide** [comment]
I just tried the demo page as suggested and `Facebook`, `Twitter` worked, but I couldn't find `Telegram` on the demo list.

I use Chromium (65), and `Facebook` isn't working yet.
