### ISSUE TITLE
Override Network

### ISSUE THREAD

**Issue by icemancast** [nicolasbeauvais/vue-social-sharing#79]
How do you pass data to an override network whether it's a popup and/or new window. The new window/popup is another vue component.

**Comment by nicolasbeauvais** [comment]
Hello @icemancast,

the window/popup is not a vue component but a native popup created by the javascript `window.open(...)` method.

Let's say you want to override the Facebook sharing link for some reason.

First, you need to define the new sharing link, you can find the default setup [in this file](https://github.com/nicolasbeauvais/vue-social-sharing/blob/master/src/networks.json):

```javascript
new Vue({
  data: {
    overriddenNetworks: {
      "facebook": {
        "sharer": "https://www.facebook.com/sharer/sharer.php?u=@url&title=@title",
        "type": "popup"
      },
    }
  }
});
```
Parameters from your `<vue-social-sharing>` instance to the sharing link are listed in this table:
https://github.com/nicolasbeauvais/vue-social-sharing#available-properties

You can add any of them to your link using the following syntax: `@parameter` like:
`"https://www.facebook.com/sharer/sharer.php?something=@hashtags`

Once you defined your sharing link in an object like we did previously you just need to pass it to your `<vue-social-sharing>` instance:

```html
<social-sharing ...:networks="overriddenNetworks" inline-template>
    ...
</social-sharing>
```  

Hope this makes it more clear to you and that I understood your question correctly.
