### ISSUE TITLE
How to change title, description and image for facebook share button?

### ISSUE THREAD

**Issue by bernarddoci** [nicolasbeauvais/vue-social-sharing#81]
Hi Nicolas,

Thank you for this great vuejs plugin. It has been very helpful to me.
But, I have a slightly small issue that I can not seem to get the hang of it.
The issue is as follows: 
Whenever I click the share to social media button, I am trying to share the specific image, title and description of the current selected item(in this case a car in my website). But what happens is that neither the image, title or description does not change but stays the same as defined in the meta tags inside the index.html file.

Please provide me with a detailed answer about this issue, because the plugin is very helpful to me.

**Comment by nicolasbeauvais** [comment]
Hello @bernarddoci,

Facebook/Twitter/LinkedIn use their own graph API to fetch the data used in the sharing dialog, so to customize the content you would like to share you need to setup meta tags on your page.

More info here #69
