### ISSUE TITLE
Dinamic content

### ISSUE THREAD

**Issue by miljko1984** [nicolasbeauvais/vue-social-sharing#83]
How to insert dinamic content in description prop, betwen static content?

data() {
			return {
                descriptions: "Hi there! {{ here need dinamic content }} here is more static content"
}
}
Thanks in advance

**Comment by nicolasbeauvais** [comment]
Hello @miljko1984,

For that, you can use a [Vuejs Computed Properties](https://vuejs.org/v2/guide/computed.html):

```javascript
new Vue({
  data() {
    someProperty: 'something',
  },

  computed: {
    dynamicDescription() {
      return `Hi there! ${this.someProperty} here is more static content`;
    }
  }
});
```

```html
<social-sharing description="dynamicDescription" inline-template>
  ...
</social-sharing
```

**Comment by miljko1984** [comment]
Hello @nicolasbeauvais,

Thank you very much!
