### ISSUE TITLE
Adding dynamic class on network tag always undefined

### ISSUE THREAD

**Issue by brickgale** [nicolasbeauvais/vue-social-sharing#86]
I think this is due to using createElement on render function... I was trying to put a 'disabled' class on it passed via props from my component using boolean.

**Comment by cristovao-trevisan** [comment]
It's due to inline-template, which takes you inner code as the template but uses the social-sharing scope to get variables

**Comment by cristovao-trevisan** [comment]
My temporary (most likely for ever tough) fix is to wrap extra properties, like so:

import SocialSharing from 'vue-social-sharing'

```js
export default {
  ...SocialSharing,
  props: {
    ...SocialSharing.props,
    test: { type: String, default: 'It does not work' },
  },
}
```
And use it like any component:

```vue
<template>
  <SocialSharing
    ...
    test='It works'
  >
    <div> {{ test }} </div>
  </SocialSharing>
<template>
<script>
import SocialSharing from './SocialSharing'

export default {
  name: 'SocialBar',
  components: { SocialSharing }
}
</script>
```

**Comment by cristovao-trevisan** [comment]
A possible permanent solution for this is to add `template: '<div> <slot /> </div>'` to the SocialSharing comonent and export Network as a separated component.
