### ISSUE TITLE
FB Share won't come with image

### ISSUE THREAD

**Issue by linweigao** [nicolasbeauvais/vue-social-sharing#88]
Hi there,

We are using this component for FB share. For the very first time of sharing a link, assuming this link is not shared before. The image will not come sometimes.

**Comment by nicolasbeauvais** [comment]
Hello @linweigao ,

are you using Facebook graph meta tags as advised in this similar issue #69 ?

Facebook/Twitter/LinkedIn need you to use meta tags attribute to specify your image path and do not accept it in their sharing link.

**Comment by linweigao** [comment]
Thank you. It looks like a open graph issue with FB.
